// Copyright 2023 MongoDB Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys             *ApiKeyDefinition                `json:",omitempty"`
	CloudProviderConfig *DataLakeCloudProviderConfigView `json:",omitempty"`
	DataProcessRegion   *DataLakeDataProcessRegionView   `json:",omitempty"`
	EndDate             *float64                         `json:",omitempty"`
	GroupId             *string                          `json:",omitempty"`
	SkipRoleValidation  *bool                            `json:",omitempty"`
	StartDate           *float64                         `json:",omitempty"`
	Storage             *DataLakeStorageView             `json:",omitempty"`
	TenantName          *string                          `json:",omitempty"`
	Hostnames           []string                         `json:",omitempty"`
	State               *string                          `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}

// DataLakeCloudProviderConfigView is autogenerated from the json schema
type DataLakeCloudProviderConfigView struct {
	Aws *DataLakeAWSCloudProviderConfigView `json:",omitempty"`
}

// DataLakeAWSCloudProviderConfigView is autogenerated from the json schema
type DataLakeAWSCloudProviderConfigView struct {
	ExternalId        *string `json:",omitempty"`
	IamAssumedRoleARN *string `json:",omitempty"`
	IamUserARN        *string `json:",omitempty"`
	RoleId            *string `json:",omitempty"`
	TestS3Bucket      *string `json:",omitempty"`
}

// DataLakeDataProcessRegionView is autogenerated from the json schema
type DataLakeDataProcessRegionView struct {
	CloudProvider *string `json:",omitempty"`
	Region        *string `json:",omitempty"`
}

// DataLakeStorageView is autogenerated from the json schema
type DataLakeStorageView struct {
	Databases []DataLakeDatabaseView `json:",omitempty"`
	Stores    []StoreDetail          `json:",omitempty"`
}

// DataLakeDatabaseView is autogenerated from the json schema
type DataLakeDatabaseView struct {
	Collections            []DataLakeDatabaseCollectionView `json:",omitempty"`
	MaxWildcardCollections *int                             `json:",omitempty"`
	Name                   *string                          `json:",omitempty"`
	Views                  []DataLakeViewView               `json:",omitempty"`
}

// DataLakeDatabaseCollectionView is autogenerated from the json schema
type DataLakeDatabaseCollectionView struct {
	DataSources []DataLakeDatabaseDataSourceView `json:",omitempty"`
	Name        *string                          `json:",omitempty"`
}

// DataLakeDatabaseDataSourceView is autogenerated from the json schema
type DataLakeDatabaseDataSourceView struct {
	AllowInsecure   *bool    `json:",omitempty"`
	Collection      *string  `json:",omitempty"`
	CollectionRegex *string  `json:",omitempty"`
	Database        *string  `json:",omitempty"`
	DefaultFormat   *string  `json:",omitempty"`
	Path            *string  `json:",omitempty"`
	StoreName       *string  `json:",omitempty"`
	Urls            []string `json:",omitempty"`
}

// DataLakeViewView is autogenerated from the json schema
type DataLakeViewView struct {
	Name     *string `json:",omitempty"`
	Pipeline *string `json:",omitempty"`
	Source   *string `json:",omitempty"`
}

// StoreDetail is autogenerated from the json schema
type StoreDetail struct {
	Name                     *string  `json:",omitempty"`
	Provider                 *string  `json:",omitempty"`
	Region                   *string  `json:",omitempty"`
	Bucket                   *string  `json:",omitempty"`
	Prefix                   *string  `json:",omitempty"`
	Delimiter                *string  `json:",omitempty"`
	IncludeTags              *bool    `json:",omitempty"`
	AdditionalStorageClasses []string `json:",omitempty"`
}
