// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys                       *ApiKey `json:",omitempty"`
	GroupId                       *string `json:",omitempty"`
	EndpointServiceId             *string `json:",omitempty"`
	InterfaceEndpointConnectionId *string `json:",omitempty"`
	ConnectionStatus              *string `json:",omitempty"`
	ErrorMessage                  *string `json:",omitempty"`
}

// ApiKey is autogenerated from the json schema
type ApiKey struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
