dir: testutil/mocksvc
structname: '{{.InterfaceName}}'
pkgname: mocksvc
template: testify
template-data:
  unroll-variadic: true
filename: "{{ .InterfaceName | snakecase }}.go"
packages:
  github.com/mongodb/mongodbatlas-cloudformation-resources/teams/cmd/resource/team-user:
    interfaces:
      TeamUsersAPI: {}
  go.mongodb.org/atlas-sdk/v20231115014/admin:
    interfaces:
      AtlasSearchApi: {}
