package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	TPSCode            *encoding.String   `json:"TPSCode,omitempty"`
	Title              *encoding.String   `json:"Title,omitempty"`
	CoverSheetIncluded *encoding.Bool     `json:"CoverSheetIncluded,omitempty"`
	DueDate            *encoding.String   `json:"DueDate,omitempty"`
	ApprovalDate       *encoding.String   `json:"ApprovalDate,omitempty"`
	Memo               Memo               `json:"Memo,omitempty"`
	SecondCopyOfMemo   Memo               `json:"SecondCopyOfMemo,omitempty"`
	TestCode           *encoding.String   `json:"TestCode,omitempty"`
	Authors            []*encoding.String `json:"Authors,omitempty"`
}

// Memo is autogenerated from the json schema
type Memo struct {
	Heading *encoding.String
	Body    *encoding.String
}
