// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile       *string  `json:",omitempty"`
	ProjectId     *string  `json:",omitempty"`
	IntegrationId *string  `json:",omitempty"`
	Type          *string  `json:",omitempty"`
	BucketName    *string  `json:",omitempty"`
	IamRoleId     *string  `json:",omitempty"`
	PrefixPath    *string  `json:",omitempty"`
	KmsKey        *string  `json:",omitempty"`
	LogTypes      []string `json:",omitempty"`
}
