project:
  name: quickstart-mongodb-atlas
  owner: quickstart-eng@amazon.com
  package_lambda: true
  regions:
  - us-east-1
  s3_bucket: ''
  #QSS3BucketName: $[taskcat_autobucket]
  #QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  shorten_stack_name: true
tests:
  mongodb-atlas:
    parameters:
      PublicKey: $[TASKCAT_project_ATLAS_PUBLIC_KEY]
      PrivateKey: $[TASKCAT_project_ATLAS_PRIVATE_KEY]
      OrgId: $[TASKCAT_project_ATLAS_ORD_ID]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      #RemoteAccessCIDR: 10.0.0.0/16
    s3_bucket: ''
    template: templates/taskcat-reg.yaml
  # mongodb-atlas-peering:
  #   parameters:
  #     PublicKey: $[TASKCAT_project_ATLAS_PUBLIC_KEY]
  #     PrivateKey: $[TASKCAT_project_ATLAS_PRIVATE_KEY]
  #     OrgId: $[TASKCAT_project_ATLAS_ORD_ID]
  #     QSS3BucketName: $[taskcat_autobucket]
  #     QSS3BucketRegion: $[taskcat_current_region]
  #     #RemoteAccessCIDR: 10.0.0.0/16
  #   s3_bucket: ''
  #   template: templates/taskcat-peering-qs.yaml

