// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys         *ApiKeyDefinition `json:",omitempty"`
	CreatedAt       *string           `json:",omitempty"`
	ExpiresAt       *string           `json:",omitempty"`
	ProjectId       *string           `json:",omitempty"`
	Id              *string           `json:",omitempty"`
	TotalCount      *float64          `json:",omitempty"`
	PageNum         *int              `json:",omitempty"`
	InvitationId    *string           `json:",omitempty"`
	InviterUsername *string           `json:",omitempty"`
	Roles           []string          `json:",omitempty"`
	Username        *string           `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}
