// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile               *string         `json:",omitempty"`
	ProjectId             *string         `json:",omitempty"`
	InstanceName          *string         `json:",omitempty"`
	WorkspaceName         *string         `json:",omitempty"`
	ProcessorName         *string         `json:",omitempty"`
	Pipeline              *string         `json:",omitempty"`
	State                 *string         `json:",omitempty"`
	Options               *StreamsOptions `json:",omitempty"`
	Id                    *string         `json:",omitempty"`
	Stats                 *string         `json:",omitempty"`
	Timeouts              *Timeouts       `json:",omitempty"`
	DeleteOnCreateTimeout *bool           `json:",omitempty"`
}

// StreamsOptions is autogenerated from the json schema
type StreamsOptions struct {
	Dlq *StreamsDLQ `json:",omitempty"`
}

// StreamsDLQ is autogenerated from the json schema
type StreamsDLQ struct {
	Coll           *string `json:",omitempty"`
	ConnectionName *string `json:",omitempty"`
	Db             *string `json:",omitempty"`
}

// Timeouts is autogenerated from the json schema
type Timeouts struct {
	Create *string `json:",omitempty"`
}
