// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	AwsKmsConfig *AwsKmsConfig `json:",omitempty"`
	Profile      *string       `json:",omitempty"`
	ProjectId    *string       `json:",omitempty"`
	Id           *string       `json:",omitempty"`
}

// AwsKmsConfig is autogenerated from the json schema
type AwsKmsConfig struct {
	RoleID              *string `json:",omitempty"`
	CustomerMasterKeyID *string `json:",omitempty"`
	Enabled             *bool   `json:",omitempty"`
	Region              *string `json:",omitempty"`
}
