package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	AwsKms    *AwsKms           `json:",omitempty"`
	ApiKeys   *ApiKeyDefinition `json:",omitempty"`
	ProjectId *string           `json:",omitempty"`
}

// AwsKms is autogenerated from the json schema
type AwsKms struct {
	AccessKeyID         *string `json:",omitempty"`
	CustomerMasterKeyID *string `json:",omitempty"`
	Enabled             *bool   `json:",omitempty"`
	Region              *string `json:",omitempty"`
	SecretAccessKey     *string `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
