// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile              *string         `json:",omitempty"`
	AutoDeferOnceEnabled *bool           `json:",omitempty"`
	DayOfWeek            *int            `json:",omitempty"`
	ProjectId            *string         `json:",omitempty"`
	HourOfDay            *int            `json:",omitempty"`
	StartASAP            *bool           `json:",omitempty"`
	Defer                *bool           `json:",omitempty"`
	AutoDefer            *bool           `json:",omitempty"`
	NumberOfDeferrals    *int            `json:",omitempty"`
	TimeZoneId           *string         `json:",omitempty"`
	ProtectedHours       *ProtectedHours `json:",omitempty"`
}

// ProtectedHours is autogenerated from the json schema
type ProtectedHours struct {
	StartHourOfDay *int `json:",omitempty"`
	EndHourOfDay   *int `json:",omitempty"`
}
