// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Id              *string           `json:",omitempty"`
	Profile         *string           `json:",omitempty"`
	ProjectId       *string           `json:",omitempty"`
	State           *string           `json:",omitempty"`
	Name            *string           `json:",omitempty"`
	CreatedDate     *string           `json:",omitempty"`
	LastUpdatedDate *string           `json:",omitempty"`
	Sink            *Sink             `json:",omitempty"`
	Source          *Source           `json:",omitempty"`
	Transformations []Transformations `json:",omitempty"`
}

// Sink is autogenerated from the json schema
type Sink struct {
	Type             *string           `json:",omitempty"`
	MetadataProvider *string           `json:",omitempty"`
	MetadataRegion   *string           `json:",omitempty"`
	PartitionFields  []PartitionFields `json:",omitempty"`
}

// PartitionFields is autogenerated from the json schema
type PartitionFields struct {
	FieldName *string `json:",omitempty"`
	Order     *int    `json:",omitempty"`
}

// Source is autogenerated from the json schema
type Source struct {
	Type           *string `json:",omitempty"`
	ClusterName    *string `json:",omitempty"`
	CollectionName *string `json:",omitempty"`
	DatabaseName   *string `json:",omitempty"`
	GroupId        *string `json:",omitempty"`
}

// Transformations is autogenerated from the json schema
type Transformations struct {
	Field *string `json:",omitempty"`
	Type  *string `json:",omitempty"`
}
