// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile                    *string  `json:",omitempty"`
	FederationSettingsId       *string  `json:",omitempty"`
	Name                       *string  `json:",omitempty"`
	IssuerUri                  *string  `json:",omitempty"`
	RequestBinding             *string  `json:",omitempty"`
	ResponseSignatureAlgorithm *string  `json:",omitempty"`
	AssociatedDomains          []string `json:",omitempty"`
	SsoDebugEnabled            *bool    `json:",omitempty"`
	SsoUrl                     *string  `json:",omitempty"`
	Status                     *string  `json:",omitempty"`
	OktaIdpId                  *string  `json:",omitempty"`
	IdpId                      *string  `json:",omitempty"`
	Protocol                   *string  `json:",omitempty"`
	Audience                   *string  `json:",omitempty"`
	ClientId                   *string  `json:",omitempty"`
	GroupsClaim                *string  `json:",omitempty"`
	RequestedScopes            []string `json:",omitempty"`
	UserClaim                  *string  `json:",omitempty"`
	Description                *string  `json:",omitempty"`
	AuthorizationType          *string  `json:",omitempty"`
	IdpType                    *string  `json:",omitempty"`
}
