// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile                 *string            `json:",omitempty"`
	ClientId                *string            `json:",omitempty"`
	CreatedAt               *string            `json:",omitempty"`
	ProjectId               *string            `json:",omitempty"`
	Name                    *string            `json:",omitempty"`
	Description             *string            `json:",omitempty"`
	Roles                   []string           `json:",omitempty"`
	SecretExpiresAfterHours *int               `json:",omitempty"`
	Secrets                 []SecretDefinition `json:",omitempty"`
}

// SecretDefinition is autogenerated from the json schema
type SecretDefinition struct {
	Id                *string `json:",omitempty"`
	CreatedAt         *string `json:",omitempty"`
	ExpiresAt         *string `json:",omitempty"`
	LastUsedAt        *string `json:",omitempty"`
	MaskedSecretValue *string `json:",omitempty"`
	Secret            *string `json:",omitempty"`
}
