// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile               *string       `json:",omitempty"`
	TotalCount            *int          `json:",omitempty"`
	CustomerX509          *CustomerX509 `json:",omitempty"`
	UserName              *string       `json:",omitempty"`
	MonthsUntilExpiration *int          `json:",omitempty"`
	ProjectId             *string       `json:",omitempty"`
}

// CustomerX509 is autogenerated from the json schema
type CustomerX509 struct {
	Cas *string `json:",omitempty"`
}
