// Copyright 2023 MongoDB Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys               *ApiKeyDefinition `json:",omitempty"`
	Links                 []Links           `json:",omitempty"`
	TotalCount            *int              `json:",omitempty"`
	CustomerX509          *CustomerX509     `json:",omitempty"`
	UserName              *string           `json:",omitempty"`
	MonthsUntilExpiration *int              `json:",omitempty"`
	ProjectId             *string           `json:",omitempty"`
	Results               []Certificate     `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}

// Links is autogenerated from the json schema
type Links struct {
	Rel  *string `json:",omitempty"`
	Href *string `json:",omitempty"`
}

// CustomerX509 is autogenerated from the json schema
type CustomerX509 struct {
	Cas *string `json:",omitempty"`
}

// Certificate is autogenerated from the json schema
type Certificate struct {
	UserName              *string `json:",omitempty"`
	CreatedAt             *string `json:",omitempty"`
	MonthsUntilExpiration *int    `json:",omitempty"`
	NotAfter              *string `json:",omitempty"`
	Subject               *string `json:",omitempty"`
	GroupId               *string `json:",omitempty"`
	Id                    *string `json:",omitempty"`
}
