---
AWSTemplateFormatVersion: '2010-09-09'
Description: MongoDB Atlas AWS CloudFormation Quickstart for MongoDB::Atlas::ProjectIpAccessList
Parameters:
  Profile:
    Description: "YSecret Manager Profile that contains the Atlas Programmatic keys"
    Type: String
    Default: "default"
  ProjectId:
    Description: "Unique 24-hexadecimal digit string that identifies your project"
    Type: String
    Default: ""
  IPAddress:
    Description: "IP address that you want to add to the project's IP access list"
    Type: String
    Default: ""
  IPAddressComment:
    Description: "Remark that explains the purpose or scope of this IP access list entry"
    Type: String
    Default: ""
Resources:
  AtlasProjectIPAccessList:
    Type: MongoDB::Atlas::ProjectIpAccessList
    Properties:
      ProjectId: !Ref "ProjectId"
      Profile: !Ref "Profile"
      AccessList:
      - IPAddress: !Ref "IPAddress"
        Comment: !Ref "IPAddressComment"
Outputs:
  AtlasProjectIpAccessList:
    Description: "Info on your Atlas Project IP Access List resource"
    Value: !Ref AtlasProjectIPAccessList
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName","AtlasProjectIPAccessList" ] ]

