// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Description        *string             `json:",omitempty"`
	APIUserId          *string             `json:",omitempty"`
	AwsSecretName      *string             `json:",omitempty"`
	OrgId              *string             `json:",omitempty"`
	Profile            *string             `json:",omitempty"`
	PublicKey          *string             `json:",omitempty"`
	PrivateKey         *string             `json:",omitempty"`
	AwsSecretArn       *string             `json:",omitempty"`
	Roles              []string            `json:",omitempty"`
	ProjectAssignments []ProjectAssignment `json:",omitempty"`
	ListOptions        *ListOptions        `json:",omitempty"`
}

// ProjectAssignment is autogenerated from the json schema
type ProjectAssignment struct {
	Roles     []string `json:",omitempty"`
	ProjectId *string  `json:",omitempty"`
}

// ListOptions is autogenerated from the json schema
type ListOptions struct {
	PageNum      *int  `json:",omitempty"`
	ItemsPerPage *int  `json:",omitempty"`
	IncludeCount *bool `json:",omitempty"`
}
