// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	PublicApiKey                 *string           `json:",omitempty"`
	PrivateApiKey                *string           `json:",omitempty"`
	ConnectionStringsStandard    *string           `json:",omitempty"`
	ConnectionStringsStandardSrv *string           `json:",omitempty"`
	ProjectId                    *string           `json:",omitempty"`
	TableName                    *string           `json:",omitempty"`
	DatabaseName                 *string           `json:",omitempty"`
	ClusterName                  *string           `json:",omitempty"`
	RegionName                   *string           `json:",omitempty"`
	Username                     *string           `json:",omitempty"`
	TableCNFIdentifier           *string           `json:",omitempty"`
	Labels                       []LabelDefinition `json:",omitempty"`
}

// LabelDefinition is autogenerated from the json schema
type LabelDefinition struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
