// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys            *ApiKeyDefinition            `json:",omitempty"`
	ConnectionStrings  *ConnectionStringsDefinition `json:",omitempty"`
	ProjectId          *string                      `json:",omitempty"`
	TableName          *string                      `json:",omitempty"`
	DatabaseName       *string                      `json:",omitempty"`
	ClusterName        *string                      `json:",omitempty"`
	RegionName         *string                      `json:",omitempty"`
	Username           *string                      `json:",omitempty"`
	TableCNFIdentifier *string                      `json:",omitempty"`
	Labels             []LabelDefinition            `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}

// ConnectionStringsDefinition is autogenerated from the json schema
type ConnectionStringsDefinition struct {
	Standard          *string `json:",omitempty"`
	StandardSrv       *string `json:",omitempty"`
	AwsPrivateLink    *string `json:",omitempty"`
	AwsPrivateLinkSrv *string `json:",omitempty"`
	Private           *string `json:",omitempty"`
	PrivateSrv        *string `json:",omitempty"`
}

// LabelDefinition is autogenerated from the json schema
type LabelDefinition struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
