// Generated by cdk-import
import * as cdk from 'aws-cdk-lib';
import * as constructs from 'constructs';

/**
 * Returns and edits the conditions that trigger alerts and how MongoDB Cloud notifies users. This collection remains under revision and may change. Refer to the legacy documentation for this collection in the following link.
 *
 * @schema CfnAlertConfigurationProps
 */
export interface CfnAlertConfigurationProps {
  /**
   * @schema CfnAlertConfigurationProps#ApiKeys
   */
  readonly apiKeys?: ApiKeyDefinition;

  /**
   * Flag that indicates whether someone enabled this alert configuration for the specified project.
   *
   * @schema CfnAlertConfigurationProps#Enabled
   */
  readonly enabled?: boolean;

  /**
   * Event type that triggers an alert.
   *
   * @schema CfnAlertConfigurationProps#EventTypeName
   */
  readonly eventTypeName?: CfnAlertConfigurationPropsEventTypeName;

  /**
   * List of rules that determine whether MongoDB Cloud checks an object for the alert configuration. You can filter using the matchers array if the **eventTypeName** specifies an event for a host, replica set, or sharded cluster.
   *
   * @schema CfnAlertConfigurationProps#Matchers
   */
  readonly matchers?: Matcher[];

  /**
   * Threshold for the metric that, when exceeded, triggers an alert. The resource returns this parameter when '"eventTypeName" : "OUTSIDE_METRIC_THRESHOLD"'.
   *
   * @schema CfnAlertConfigurationProps#MetricThreshold
   */
  readonly metricThreshold?: MetricThresholdView;

  /**
   * List that contains the targets that MongoDB Cloud sends notifications.
   *
   * @schema CfnAlertConfigurationProps#Notifications
   */
  readonly notifications?: NotificationView[];

  /**
   * Limit that triggers an alert when exceeded. The resource returns this parameter when **eventTypeName** has not been set to 'OUTSIDE_METRIC_THRESHOLD'.
   *
   * @schema CfnAlertConfigurationProps#Threshold
   */
  readonly threshold?: IntegerThresholdView;

}

/**
 * Converts an object of type 'CfnAlertConfigurationProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnAlertConfigurationProps(obj: CfnAlertConfigurationProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ApiKeys': toJson_ApiKeyDefinition(obj.apiKeys),
    'Enabled': obj.enabled,
    'EventTypeName': obj.eventTypeName,
    'Matchers': obj.matchers?.map(y => toJson_Matcher(y)),
    'MetricThreshold': toJson_MetricThresholdView(obj.metricThreshold),
    'Notifications': obj.notifications?.map(y => toJson_NotificationView(y)),
    'Threshold': toJson_IntegerThresholdView(obj.threshold),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema ApiKeyDefinition
 */
export interface ApiKeyDefinition {
  /**
   * @schema ApiKeyDefinition#PrivateKey
   */
  readonly privateKey?: string;

  /**
   * @schema ApiKeyDefinition#PublicKey
   */
  readonly publicKey?: string;

}

/**
 * Converts an object of type 'ApiKeyDefinition' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApiKeyDefinition(obj: ApiKeyDefinition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'PrivateKey': obj.privateKey,
    'PublicKey': obj.publicKey,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Event type that triggers an alert.
 *
 * @schema CfnAlertConfigurationPropsEventTypeName
 */
export enum CfnAlertConfigurationPropsEventTypeName {
  /** AWS_ENCRYPTION_KEY_NEEDS_ROTATION */
  AWS_ENCRYPTION_KEY_NEEDS_ROTATION = 'AWS_ENCRYPTION_KEY_NEEDS_ROTATION',
  /** AZURE_ENCRYPTION_KEY_NEEDS_ROTATION */
  AZURE_ENCRYPTION_KEY_NEEDS_ROTATION = 'AZURE_ENCRYPTION_KEY_NEEDS_ROTATION',
  /** CLUSTER_MONGOS_IS_MISSING */
  CLUSTER_MONGOS_IS_MISSING = 'CLUSTER_MONGOS_IS_MISSING',
  /** CPS_RESTORE_FAILED */
  CPS_RESTORE_FAILED = 'CPS_RESTORE_FAILED',
  /** CPS_RESTORE_SUCCESSFUL */
  CPS_RESTORE_SUCCESSFUL = 'CPS_RESTORE_SUCCESSFUL',
  /** CPS_SNAPSHOT_BEHIND */
  CPS_SNAPSHOT_BEHIND = 'CPS_SNAPSHOT_BEHIND',
  /** CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED */
  CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED = 'CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED',
  /** CPS_SNAPSHOT_FALLBACK_FAILED */
  CPS_SNAPSHOT_FALLBACK_FAILED = 'CPS_SNAPSHOT_FALLBACK_FAILED',
  /** CPS_SNAPSHOT_FALLBACK_SUCCESSFUL */
  CPS_SNAPSHOT_FALLBACK_SUCCESSFUL = 'CPS_SNAPSHOT_FALLBACK_SUCCESSFUL',
  /** CPS_SNAPSHOT_SUCCESSFUL */
  CPS_SNAPSHOT_SUCCESSFUL = 'CPS_SNAPSHOT_SUCCESSFUL',
  /** CREDIT_CARD_ABOUT_TO_EXPIRE */
  CREDIT_CARD_ABOUT_TO_EXPIRE = 'CREDIT_CARD_ABOUT_TO_EXPIRE',
  /** DAILY_BILL_OVER_THRESHOLD */
  DAILY_BILL_OVER_THRESHOLD = 'DAILY_BILL_OVER_THRESHOLD',
  /** GCP_ENCRYPTION_KEY_NEEDS_ROTATION */
  GCP_ENCRYPTION_KEY_NEEDS_ROTATION = 'GCP_ENCRYPTION_KEY_NEEDS_ROTATION',
  /** HOST_DOWN */
  HOST_DOWN = 'HOST_DOWN',
  /** JOINED_GROUP */
  JOINED_GROUP = 'JOINED_GROUP',
  /** NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK */
  NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK = 'NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK',
  /** NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK */
  NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK = 'NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK',
  /** NO_PRIMARY */
  NO_PRIMARY = 'NO_PRIMARY',
  /** OUTSIDE_METRIC_THRESHOLD */
  OUTSIDE_METRIC_THRESHOLD = 'OUTSIDE_METRIC_THRESHOLD',
  /** OUTSIDE_SERVERLESS_METRIC_THRESHOLD */
  OUTSIDE_SERVERLESS_METRIC_THRESHOLD = 'OUTSIDE_SERVERLESS_METRIC_THRESHOLD',
  /** OUTSIDE_REALM_METRIC_THRESHOLD */
  OUTSIDE_REALM_METRIC_THRESHOLD = 'OUTSIDE_REALM_METRIC_THRESHOLD',
  /** PENDING_INVOICE_OVER_THRESHOLD */
  PENDING_INVOICE_OVER_THRESHOLD = 'PENDING_INVOICE_OVER_THRESHOLD',
  /** PRIMARY_ELECTED */
  PRIMARY_ELECTED = 'PRIMARY_ELECTED',
  /** REMOVED_FROM_GROUP */
  REMOVED_FROM_GROUP = 'REMOVED_FROM_GROUP',
  /** REPLICATION_OPLOG_WINDOW_RUNNING_OUT */
  REPLICATION_OPLOG_WINDOW_RUNNING_OUT = 'REPLICATION_OPLOG_WINDOW_RUNNING_OUT',
  /** TOO_MANY_ELECTIONS */
  TOO_MANY_ELECTIONS = 'TOO_MANY_ELECTIONS',
  /** USER_ROLES_CHANGED_AUDIT */
  USER_ROLES_CHANGED_AUDIT = 'USER_ROLES_CHANGED_AUDIT',
  /** USERS_WITHOUT_MULTIFACTOR_AUTH */
  USERS_WITHOUT_MULTIFACTOR_AUTH = 'USERS_WITHOUT_MULTIFACTOR_AUTH',
}

/**
 * @schema Matcher
 */
export interface Matcher {
  /**
   * Name of the parameter in the target object that MongoDB Cloud checks. The parameter must match all rules for MongoDB Cloud to check for alert configurations.
   *
   * @schema Matcher#FieldName
   */
  readonly fieldName?: MatcherFieldName;

  /**
   * Comparison operator to apply when checking the current metric value against **matcher[n].value**.
   *
   * @schema Matcher#Operator
   */
  readonly operator?: MatcherOperator;

  /**
   * Value to match or exceed using the specified **matchers.operator**.
   *
   * @schema Matcher#Value
   */
  readonly value?: string;

}

/**
 * Converts an object of type 'Matcher' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_Matcher(obj: Matcher | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'FieldName': obj.fieldName,
    'Operator': obj.operator,
    'Value': obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MetricThresholdView
 */
export interface MetricThresholdView {
  /**
   * Human-readable label that identifies the metric against which MongoDB Cloud checks the configured **metricThreshold.threshold**.
   *
   * @schema MetricThresholdView#MetricName
   */
  readonly metricName?: MetricThresholdViewMetricName;

  /**
   * MongoDB Cloud computes the current metric value as an average.
   *
   * @schema MetricThresholdView#Mode
   */
  readonly mode?: MetricThresholdViewMode;

  /**
   * Comparison operator to apply when checking the current metric value.
   *
   * @schema MetricThresholdView#Operator
   */
  readonly operator?: MetricThresholdViewOperator;

  /**
   * Value of metric that, when exceeded, triggers an alert.
   *
   * @schema MetricThresholdView#Threshold
   */
  readonly threshold?: number;

  /**
   * Element used to express the quantity. This can be an element of time, storage capacity, and the like.
   *
   * @schema MetricThresholdView#Units
   */
  readonly units?: MetricThresholdViewUnits;

}

/**
 * Converts an object of type 'MetricThresholdView' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MetricThresholdView(obj: MetricThresholdView | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'MetricName': obj.metricName,
    'Mode': obj.mode,
    'Operator': obj.operator,
    'Threshold': obj.threshold,
    'Units': obj.units,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema NotificationView
 */
export interface NotificationView {
  /**
   * Slack API token or Bot token that MongoDB Cloud needs to send alert notifications via Slack. The resource requires this parameter when '"notifications.typeName" : "SLACK"'. If the token later becomes invalid, MongoDB Cloud sends an email to the project owners. If the token remains invalid, MongoDB Cloud removes the token.
   *
   * @schema NotificationView#ApiToken
   */
  readonly apiToken?: string;

  /**
   * Name of the Slack channel to which MongoDB Cloud sends alert notifications. The resource requires this parameter when '"notifications.typeName" : "SLACK"'.
   *
   * @schema NotificationView#ChannelName
   */
  readonly channelName?: string;

  /**
   * Datadog API Key that MongoDB Cloud needs to send alert notifications to Datadog. You can find this API key in the Datadog dashboard. The resource requires this parameter when '"notifications.typeName" : "DATADOG"'.
   *
   * @schema NotificationView#DatadogApiKey
   */
  readonly datadogApiKey?: string;

  /**
   * Datadog region that indicates which API Uniform Resource Locator (URL) to use. The resource requires this parameter when '"notifications.typeName" : "DATADOG"'.
   *
   * @schema NotificationView#DatadogRegion
   */
  readonly datadogRegion?: NotificationViewDatadogRegion;

  /**
   * Number of minutes that MongoDB Cloud waits after detecting an alert condition before it sends out the first notification.
   *
   * @schema NotificationView#DelayMin
   */
  readonly delayMin?: number;

  /**
   * Email address to which MongoDB Cloud sends alert notifications. The resource requires this parameter when '"notifications.typeName" : "EMAIL"'. You don't need to set this value to send emails to individual or groups of MongoDB Cloud users including:
   *
   * - specific MongoDB Cloud users ('"notifications.typeName" : "USER"')
   * - MongoDB Cloud users with specific project roles ('"notifications.typeName" : "GROUP"')
   * - MongoDB Cloud users with specific organization roles ('"notifications.typeName" : "ORG"')
   * - MongoDB Cloud teams ('"notifications.typeName" : "TEAM"')
   *
   * To send emails to one MongoDB Cloud user or grouping of users, set the **notifications.emailEnabled** parameter.
   *
   * @schema NotificationView#EmailAddress
   */
  readonly emailAddress?: string;

  /**
   * Flag that indicates whether MongoDB Cloud should send email notifications. The resource requires this parameter when one of the following values have been set:
   *
   * - '"notifications.typeName" : "ORG"'
   * - '"notifications.typeName" : "GROUP"'
   * - '"notifications.typeName" : "USER"'
   *
   * @schema NotificationView#EmailEnabled
   */
  readonly emailEnabled?: boolean;

  /**
   * Flowdock flow name to which MongoDB Cloud sends alert notifications. This name appears after the organization name in the Uniform Resource Locator (URL) path: 'www.flowdock.com/app/<organization-name>/<flow-name>'. The resource requires this parameter when '"notifications.typeName" : "FLOWDOCK"'.
   *
   * @schema NotificationView#FlowName
   */
  readonly flowName?: string;

  /**
   * Flowdock API token that MongoDB Cloud needs to send alert notifications to Flowdock. The resource requires this parameter when '"notifications.typeName" : "FLOWDOCK"'. If the token later becomes invalid, MongoDB Cloud sends an email to the project owners. If the token remains invalid, MongoDB Cloud removes the token.
   *
   * @schema NotificationView#FlowdockApiToken
   */
  readonly flowdockApiToken?: string;

  /**
   * Number of minutes to wait between successive notifications. MongoDB Cloud sends notifications until someone acknowledges the unacknowledged alert.
   *
   * PagerDuty, VictorOps, and OpsGenie notifications don't return this element. Configure and manage the notification interval within each of those services.
   *
   * @schema NotificationView#IntervalMin
   */
  readonly intervalMin?: number;

  /**
   * Microsoft Teams Webhook Uniform Resource Locator (URL) that MongoDB Cloud needs to send this notification via Microsoft Teams. The resource requires this parameter when '"notifications.typeName" : "MICROSOFT_TEAMS"'. If the URL later becomes invalid, MongoDB Cloud sends an email to the project owners. If the key remains invalid, MongoDB Cloud removes it.
   *
   * @schema NotificationView#MicrosoftTeamsWebhookUrl
   */
  readonly microsoftTeamsWebhookUrl?: string;

  /**
   * Mobile phone number to which MongoDB Cloud sends alert notifications. The resource requires this parameter when '"notifications.typeName" : "SMS"'.
   *
   * @schema NotificationView#MobileNumber
   */
  readonly mobileNumber?: string;

  /**
   * HipChat API token that MongoDB Cloud needs to send alert notifications to HipChat. The resource requires this parameter when '"notifications.typeName" : "HIP_CHAT"'". If the token later becomes invalid, MongoDB Cloud sends an email to the project owners. If the token remains invalid, MongoDB Cloud removes it.
   *
   * @schema NotificationView#NotificationToken
   */
  readonly notificationToken?: string;

  /**
   * API Key that MongoDB Cloud needs to send this notification via Opsgenie. The resource requires this parameter when '"notifications.typeName" : "OPS_GENIE"'. If the key later becomes invalid, MongoDB Cloud sends an email to the project owners. If the key remains invalid, MongoDB Cloud removes it.
   *
   * @schema NotificationView#OpsGenieApiKey
   */
  readonly opsGenieApiKey?: string;

  /**
   * Opsgenie region that indicates which API Uniform Resource Locator (URL) to use.
   *
   * @schema NotificationView#OpsGenieRegion
   */
  readonly opsGenieRegion?: NotificationViewOpsGenieRegion;

  /**
   * Flowdock organization name to which MongoDB Cloud sends alert notifications. This name appears after 'www.flowdock.com/app/' in the Uniform Resource Locator (URL) path. The resource requires this parameter when '"notifications.typeName" : "FLOWDOCK"'.
   *
   * @schema NotificationView#OrgName
   */
  readonly orgName?: string;

  /**
   * List that contains the one or more organization or project roles that receive the configured alert. The resource requires this parameter when '"notifications.typeName" : "GROUP"' or '"notifications.typeName" : "ORG"'. If you include this parameter, MongoDB Cloud sends alerts only to users assigned the roles you specify in the array. If you omit this parameter, MongoDB Cloud sends alerts to users assigned any role.
   *
   * @schema NotificationView#Roles
   */
  readonly roles?: NotificationViewRoles[];

  /**
   * HipChat API room name to which MongoDB Cloud sends alert notifications. The resource requires this parameter when '"notifications.typeName" : "HIP_CHAT"'".
   *
   * @schema NotificationView#RoomName
   */
  readonly roomName?: string;

  /**
   * PagerDuty service key that MongoDB Cloud needs to send notifications via PagerDuty. The resource requires this parameter when '"notifications.typeName" : "PAGER_DUTY"'. If the key later becomes invalid, MongoDB Cloud sends an email to the project owners. If the key remains invalid, MongoDB Cloud removes it.
   *
   * @schema NotificationView#ServiceKey
   */
  readonly serviceKey?: string;

  /**
   * Degree of seriousness given to this notification.
   *
   * @schema NotificationView#Severity
   */
  readonly severity?: NotificationViewSeverity;

  /**
   * Flag that indicates whether MongoDB Cloud should send text message notifications. The resource requires this parameter when one of the following values have been set:
   *
   * - '"notifications.typeName" : "ORG"'
   * - '"notifications.typeName" : "GROUP"'
   * - '"notifications.typeName" : "USER"'
   *
   * @schema NotificationView#SmsEnabled
   */
  readonly smsEnabled?: boolean;

  /**
   * Unique 24-hexadecimal digit string that identifies one MongoDB Cloud team. The resource requires this parameter when '"notifications.typeName" : "TEAM"'.
   *
   * @schema NotificationView#TeamId
   */
  readonly teamId?: string;

  /**
   * Name of the MongoDB Cloud team that receives this notification. The resource requires this parameter when '"notifications.typeName" : "TEAM"'.
   *
   * @schema NotificationView#TeamName
   */
  readonly teamName?: string;

  /**
   * Human-readable label that displays the alert notification type.
   *
   * @schema NotificationView#TypeName
   */
  readonly typeName?: NotificationViewTypeName;

  /**
   * MongoDB Cloud username of the person to whom MongoDB Cloud sends notifications. Specify only MongoDB Cloud users who belong to the project that owns the alert configuration. The resource requires this parameter when '"notifications.typeName" : "USER"'.
   *
   * @schema NotificationView#Username
   */
  readonly username?: string;

  /**
   * API key that MongoDB Cloud needs to send alert notifications to Splunk On-Call. The resource requires this parameter when '"notifications.typeName" : "VICTOR_OPS"'. If the key later becomes invalid, MongoDB Cloud sends an email to the project owners. If the key remains invalid, MongoDB Cloud removes it.
   *
   * @schema NotificationView#VictorOpsApiKey
   */
  readonly victorOpsApiKey?: string;

  /**
   * Routing key that MongoDB Cloud needs to send alert notifications to Splunk On-Call. The resource requires this parameter when '"notifications.typeName" : "VICTOR_OPS"'. If the key later becomes invalid, MongoDB Cloud sends an email to the project owners. If the key remains invalid, MongoDB Cloud removes it.
   *
   * @schema NotificationView#VictorOpsRoutingKey
   */
  readonly victorOpsRoutingKey?: string;

  /**
   * An optional field for your webhook secret.
   *
   * @schema NotificationView#WebhookSecret
   */
  readonly webhookSecret?: string;

  /**
   * Your webhook URL.
   *
   * @schema NotificationView#WebhookUrl
   */
  readonly webhookUrl?: string;

}

/**
 * Converts an object of type 'NotificationView' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_NotificationView(obj: NotificationView | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ApiToken': obj.apiToken,
    'ChannelName': obj.channelName,
    'DatadogApiKey': obj.datadogApiKey,
    'DatadogRegion': obj.datadogRegion,
    'DelayMin': obj.delayMin,
    'EmailAddress': obj.emailAddress,
    'EmailEnabled': obj.emailEnabled,
    'FlowName': obj.flowName,
    'FlowdockApiToken': obj.flowdockApiToken,
    'IntervalMin': obj.intervalMin,
    'MicrosoftTeamsWebhookUrl': obj.microsoftTeamsWebhookUrl,
    'MobileNumber': obj.mobileNumber,
    'NotificationToken': obj.notificationToken,
    'OpsGenieApiKey': obj.opsGenieApiKey,
    'OpsGenieRegion': obj.opsGenieRegion,
    'OrgName': obj.orgName,
    'Roles': obj.roles?.map(y => y),
    'RoomName': obj.roomName,
    'ServiceKey': obj.serviceKey,
    'Severity': obj.severity,
    'SmsEnabled': obj.smsEnabled,
    'TeamId': obj.teamId,
    'TeamName': obj.teamName,
    'TypeName': obj.typeName,
    'Username': obj.username,
    'VictorOpsApiKey': obj.victorOpsApiKey,
    'VictorOpsRoutingKey': obj.victorOpsRoutingKey,
    'WebhookSecret': obj.webhookSecret,
    'WebhookUrl': obj.webhookUrl,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema IntegerThresholdView
 */
export interface IntegerThresholdView {
  /**
   * Comparison operator to apply when checking the current metric value.
   *
   * @schema IntegerThresholdView#Operator
   */
  readonly operator?: IntegerThresholdViewOperator;

  /**
   * Value of metric that, when exceeded, triggers an alert.
   *
   * @schema IntegerThresholdView#Threshold
   */
  readonly threshold?: number;

  /**
   * Element used to express the quantity. This can be an element of time, storage capacity, and the like.
   *
   * @schema IntegerThresholdView#Units
   */
  readonly units?: IntegerThresholdViewUnits;

}

/**
 * Converts an object of type 'IntegerThresholdView' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_IntegerThresholdView(obj: IntegerThresholdView | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Operator': obj.operator,
    'Threshold': obj.threshold,
    'Units': obj.units,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Name of the parameter in the target object that MongoDB Cloud checks. The parameter must match all rules for MongoDB Cloud to check for alert configurations.
 *
 * @schema MatcherFieldName
 */
export enum MatcherFieldName {
  /** CLUSTER_NAME */
  CLUSTER_NAME = 'CLUSTER_NAME',
  /** HOSTNAME */
  HOSTNAME = 'HOSTNAME',
  /** HOSTNAME_AND_PORT */
  HOSTNAME_AND_PORT = 'HOSTNAME_AND_PORT',
  /** PORT */
  PORT = 'PORT',
  /** REPLICA_SET_NAME */
  REPLICA_SET_NAME = 'REPLICA_SET_NAME',
  /** SHARD_NAME */
  SHARD_NAME = 'SHARD_NAME',
  /** TYPE_NAME */
  TYPE_NAME = 'TYPE_NAME',
}

/**
 * Comparison operator to apply when checking the current metric value against **matcher[n].value**.
 *
 * @schema MatcherOperator
 */
export enum MatcherOperator {
  /** EQUALS */
  EQUALS = 'EQUALS',
  /** CONTAINS */
  CONTAINS = 'CONTAINS',
  /** STARTS_WITH */
  STARTS_WITH = 'STARTS_WITH',
  /** ENDS_WITH */
  ENDS_WITH = 'ENDS_WITH',
  /** NOT_EQUALS */
  NOT_EQUALS = 'NOT_EQUALS',
  /** NOT_CONTAINS */
  NOT_CONTAINS = 'NOT_CONTAINS',
  /** REGEX */
  REGEX = 'REGEX',
}

/**
 * Human-readable label that identifies the metric against which MongoDB Cloud checks the configured **metricThreshold.threshold**.
 *
 * @schema MetricThresholdViewMetricName
 */
export enum MetricThresholdViewMetricName {
  /** ASSERT_MSG */
  ASSERT_MSG = 'ASSERT_MSG',
  /** ASSERT_REGULAR */
  ASSERT_REGULAR = 'ASSERT_REGULAR',
  /** ASSERT_USER */
  ASSERT_USER = 'ASSERT_USER',
  /** ASSERT_WARNING */
  ASSERT_WARNING = 'ASSERT_WARNING',
  /** AVG_COMMAND_EXECUTION_TIME */
  AVG_COMMAND_EXECUTION_TIME = 'AVG_COMMAND_EXECUTION_TIME',
  /** AVG_READ_EXECUTION_TIME */
  AVG_READ_EXECUTION_TIME = 'AVG_READ_EXECUTION_TIME',
  /** AVG_WRITE_EXECUTION_TIME */
  AVG_WRITE_EXECUTION_TIME = 'AVG_WRITE_EXECUTION_TIME',
  /** BACKGROUND_FLUSH_AVG */
  BACKGROUND_FLUSH_AVG = 'BACKGROUND_FLUSH_AVG',
  /** CACHE_BYTES_READ_INTO */
  CACHE_BYTES_READ_INTO = 'CACHE_BYTES_READ_INTO',
  /** CACHE_BYTES_WRITTEN_FROM */
  CACHE_BYTES_WRITTEN_FROM = 'CACHE_BYTES_WRITTEN_FROM',
  /** CACHE_USAGE_DIRTY */
  CACHE_USAGE_DIRTY = 'CACHE_USAGE_DIRTY',
  /** CACHE_USAGE_USED */
  CACHE_USAGE_USED = 'CACHE_USAGE_USED',
  /** COMPUTED_MEMORY */
  COMPUTED_MEMORY = 'COMPUTED_MEMORY',
  /** CONNECTIONS */
  CONNECTIONS = 'CONNECTIONS',
  /** CONNECTIONS_MAX */
  CONNECTIONS_MAX = 'CONNECTIONS_MAX',
  /** CONNECTIONS_PERCENT */
  CONNECTIONS_PERCENT = 'CONNECTIONS_PERCENT',
  /** CURSORS_TOTAL_CLIENT_CURSORS_SIZE */
  CURSORS_TOTAL_CLIENT_CURSORS_SIZE = 'CURSORS_TOTAL_CLIENT_CURSORS_SIZE',
  /** CURSORS_TOTAL_OPEN */
  CURSORS_TOTAL_OPEN = 'CURSORS_TOTAL_OPEN',
  /** CURSORS_TOTAL_TIMED_OUT */
  CURSORS_TOTAL_TIMED_OUT = 'CURSORS_TOTAL_TIMED_OUT',
  /** DB_DATA_SIZE_TOTAL */
  DB_DATA_SIZE_TOTAL = 'DB_DATA_SIZE_TOTAL',
  /** DB_INDEX_SIZE_TOTAL */
  DB_INDEX_SIZE_TOTAL = 'DB_INDEX_SIZE_TOTAL',
  /** DB_STORAGE_TOTAL */
  DB_STORAGE_TOTAL = 'DB_STORAGE_TOTAL',
  /** DISK_PARTITION_SPACE_USED_DATA */
  DISK_PARTITION_SPACE_USED_DATA = 'DISK_PARTITION_SPACE_USED_DATA',
  /** DISK_PARTITION_SPACE_USED_INDEX */
  DISK_PARTITION_SPACE_USED_INDEX = 'DISK_PARTITION_SPACE_USED_INDEX',
  /** DISK_PARTITION_SPACE_USED_JOURNAL */
  DISK_PARTITION_SPACE_USED_JOURNAL = 'DISK_PARTITION_SPACE_USED_JOURNAL',
  /** DISK_PARTITION_UTILIZATION_DATA */
  DISK_PARTITION_UTILIZATION_DATA = 'DISK_PARTITION_UTILIZATION_DATA',
  /** DISK_PARTITION_UTILIZATION_INDEX */
  DISK_PARTITION_UTILIZATION_INDEX = 'DISK_PARTITION_UTILIZATION_INDEX',
  /** DISK_PARTITION_UTILIZATION_JOURNAL */
  DISK_PARTITION_UTILIZATION_JOURNAL = 'DISK_PARTITION_UTILIZATION_JOURNAL',
  /** DOCUMENT_DELETED */
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  /** DOCUMENT_INSERTED */
  DOCUMENT_INSERTED = 'DOCUMENT_INSERTED',
  /** DOCUMENT_RETURNED */
  DOCUMENT_RETURNED = 'DOCUMENT_RETURNED',
  /** DOCUMENT_UPDATED */
  DOCUMENT_UPDATED = 'DOCUMENT_UPDATED',
  /** EXTRA_INFO_PAGE_FAULTS */
  EXTRA_INFO_PAGE_FAULTS = 'EXTRA_INFO_PAGE_FAULTS',
  /** FTS_DISK_UTILIZATION */
  FTS_DISK_UTILIZATION = 'FTS_DISK_UTILIZATION',
  /** FTS_MEMORY_MAPPED */
  FTS_MEMORY_MAPPED = 'FTS_MEMORY_MAPPED',
  /** FTS_MEMORY_RESIDENT */
  FTS_MEMORY_RESIDENT = 'FTS_MEMORY_RESIDENT',
  /** FTS_MEMORY_VIRTUAL */
  FTS_MEMORY_VIRTUAL = 'FTS_MEMORY_VIRTUAL',
  /** FTS_PROCESS_CPU_KERNEL */
  FTS_PROCESS_CPU_KERNEL = 'FTS_PROCESS_CPU_KERNEL',
  /** FTS_PROCESS_CPU_USER */
  FTS_PROCESS_CPU_USER = 'FTS_PROCESS_CPU_USER',
  /** GLOBAL_ACCESSES_NOT_IN_MEMORY */
  GLOBAL_ACCESSES_NOT_IN_MEMORY = 'GLOBAL_ACCESSES_NOT_IN_MEMORY',
  /** GLOBAL_LOCK_CURRENT_QUEUE_READERS */
  GLOBAL_LOCK_CURRENT_QUEUE_READERS = 'GLOBAL_LOCK_CURRENT_QUEUE_READERS',
  /** GLOBAL_LOCK_CURRENT_QUEUE_TOTAL */
  GLOBAL_LOCK_CURRENT_QUEUE_TOTAL = 'GLOBAL_LOCK_CURRENT_QUEUE_TOTAL',
  /** GLOBAL_LOCK_CURRENT_QUEUE_WRITERS */
  GLOBAL_LOCK_CURRENT_QUEUE_WRITERS = 'GLOBAL_LOCK_CURRENT_QUEUE_WRITERS',
  /** GLOBAL_LOCK_PERCENTAGE */
  GLOBAL_LOCK_PERCENTAGE = 'GLOBAL_LOCK_PERCENTAGE',
  /** GLOBAL_PAGE_FAULT_EXCEPTIONS_THROWN */
  GLOBAL_PAGE_FAULT_EXCEPTIONS_THROWN = 'GLOBAL_PAGE_FAULT_EXCEPTIONS_THROWN',
  /** INDEX_COUNTERS_BTREE_ACCESSES */
  INDEX_COUNTERS_BTREE_ACCESSES = 'INDEX_COUNTERS_BTREE_ACCESSES',
  /** INDEX_COUNTERS_BTREE_HITS */
  INDEX_COUNTERS_BTREE_HITS = 'INDEX_COUNTERS_BTREE_HITS',
  /** INDEX_COUNTERS_BTREE_MISS_RATIO */
  INDEX_COUNTERS_BTREE_MISS_RATIO = 'INDEX_COUNTERS_BTREE_MISS_RATIO',
  /** INDEX_COUNTERS_BTREE_MISSES */
  INDEX_COUNTERS_BTREE_MISSES = 'INDEX_COUNTERS_BTREE_MISSES',
  /** JOURNALING_COMMITS_IN_WRITE_LOCK */
  JOURNALING_COMMITS_IN_WRITE_LOCK = 'JOURNALING_COMMITS_IN_WRITE_LOCK',
  /** JOURNALING_MB */
  JOURNALING_MB = 'JOURNALING_MB',
  /** JOURNALING_WRITE_DATA_FILES_MB */
  JOURNALING_WRITE_DATA_FILES_MB = 'JOURNALING_WRITE_DATA_FILES_MB',
  /** LOGICAL_SIZE */
  LOGICAL_SIZE = 'LOGICAL_SIZE',
  /** MEMORY_MAPPED */
  MEMORY_MAPPED = 'MEMORY_MAPPED',
  /** MEMORY_RESIDENT */
  MEMORY_RESIDENT = 'MEMORY_RESIDENT',
  /** MEMORY_VIRTUAL */
  MEMORY_VIRTUAL = 'MEMORY_VIRTUAL',
  /** MUNIN_CPU_IOWAIT */
  MUNIN_CPU_IOWAIT = 'MUNIN_CPU_IOWAIT',
  /** MUNIN_CPU_IRQ */
  MUNIN_CPU_IRQ = 'MUNIN_CPU_IRQ',
  /** MUNIN_CPU_NICE */
  MUNIN_CPU_NICE = 'MUNIN_CPU_NICE',
  /** MUNIN_CPU_SOFTIRQ */
  MUNIN_CPU_SOFTIRQ = 'MUNIN_CPU_SOFTIRQ',
  /** MUNIN_CPU_STEAL */
  MUNIN_CPU_STEAL = 'MUNIN_CPU_STEAL',
  /** MUNIN_CPU_SYSTEM */
  MUNIN_CPU_SYSTEM = 'MUNIN_CPU_SYSTEM',
  /** MUNIN_CPU_USER */
  MUNIN_CPU_USER = 'MUNIN_CPU_USER',
  /** NETWORK_BYTES_IN */
  NETWORK_BYTES_IN = 'NETWORK_BYTES_IN',
  /** NETWORK_BYTES_OUT */
  NETWORK_BYTES_OUT = 'NETWORK_BYTES_OUT',
  /** NETWORK_NUM_REQUESTS */
  NETWORK_NUM_REQUESTS = 'NETWORK_NUM_REQUESTS',
  /** NORMALIZED_FTS_PROCESS_CPU_KERNEL */
  NORMALIZED_FTS_PROCESS_CPU_KERNEL = 'NORMALIZED_FTS_PROCESS_CPU_KERNEL',
  /** NORMALIZED_FTS_PROCESS_CPU_USER */
  NORMALIZED_FTS_PROCESS_CPU_USER = 'NORMALIZED_FTS_PROCESS_CPU_USER',
  /** NORMALIZED_SYSTEM_CPU_STEAL */
  NORMALIZED_SYSTEM_CPU_STEAL = 'NORMALIZED_SYSTEM_CPU_STEAL',
  /** NORMALIZED_SYSTEM_CPU_USER */
  NORMALIZED_SYSTEM_CPU_USER = 'NORMALIZED_SYSTEM_CPU_USER',
  /** OPCOUNTER_CMD */
  OPCOUNTER_CMD = 'OPCOUNTER_CMD',
  /** OPCOUNTER_DELETE */
  OPCOUNTER_DELETE = 'OPCOUNTER_DELETE',
  /** OPCOUNTER_GETMORE */
  OPCOUNTER_GETMORE = 'OPCOUNTER_GETMORE',
  /** OPCOUNTER_INSERT */
  OPCOUNTER_INSERT = 'OPCOUNTER_INSERT',
  /** OPCOUNTER_QUERY */
  OPCOUNTER_QUERY = 'OPCOUNTER_QUERY',
  /** OPCOUNTER_REPL_CMD */
  OPCOUNTER_REPL_CMD = 'OPCOUNTER_REPL_CMD',
  /** OPCOUNTER_REPL_DELETE */
  OPCOUNTER_REPL_DELETE = 'OPCOUNTER_REPL_DELETE',
  /** OPCOUNTER_REPL_INSERT */
  OPCOUNTER_REPL_INSERT = 'OPCOUNTER_REPL_INSERT',
  /** OPCOUNTER_REPL_UPDATE */
  OPCOUNTER_REPL_UPDATE = 'OPCOUNTER_REPL_UPDATE',
  /** OPCOUNTER_UPDATE */
  OPCOUNTER_UPDATE = 'OPCOUNTER_UPDATE',
  /** OPERATIONS_SCAN_AND_ORDER */
  OPERATIONS_SCAN_AND_ORDER = 'OPERATIONS_SCAN_AND_ORDER',
  /** OPLOG_MASTER_LAG_TIME_DIFF */
  OPLOG_MASTER_LAG_TIME_DIFF = 'OPLOG_MASTER_LAG_TIME_DIFF',
  /** OPLOG_MASTER_TIME */
  OPLOG_MASTER_TIME = 'OPLOG_MASTER_TIME',
  /** OPLOG_MASTER_TIME_ESTIMATED_TTL */
  OPLOG_MASTER_TIME_ESTIMATED_TTL = 'OPLOG_MASTER_TIME_ESTIMATED_TTL',
  /** OPLOG_RATE_GB_PER_HOUR */
  OPLOG_RATE_GB_PER_HOUR = 'OPLOG_RATE_GB_PER_HOUR',
  /** OPLOG_SLAVE_LAG_MASTER_TIME */
  OPLOG_SLAVE_LAG_MASTER_TIME = 'OPLOG_SLAVE_LAG_MASTER_TIME',
  /** QUERY_EXECUTOR_SCANNED */
  QUERY_EXECUTOR_SCANNED = 'QUERY_EXECUTOR_SCANNED',
  /** QUERY_EXECUTOR_SCANNED_OBJECTS */
  QUERY_EXECUTOR_SCANNED_OBJECTS = 'QUERY_EXECUTOR_SCANNED_OBJECTS',
  /** QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED */
  QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED = 'QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED',
  /** QUERY_TARGETING_SCANNED_PER_RETURNED */
  QUERY_TARGETING_SCANNED_PER_RETURNED = 'QUERY_TARGETING_SCANNED_PER_RETURNED',
  /** RESTARTS_IN_LAST_HOUR */
  RESTARTS_IN_LAST_HOUR = 'RESTARTS_IN_LAST_HOUR',
  /** SERVERLESS_CONNECTIONS */
  SERVERLESS_CONNECTIONS = 'SERVERLESS_CONNECTIONS',
  /** SERVERLESS_CONNECTIONS_PERCENT */
  SERVERLESS_CONNECTIONS_PERCENT = 'SERVERLESS_CONNECTIONS_PERCENT',
  /** SERVERLESS_DATA_SIZE_TOTAL */
  SERVERLESS_DATA_SIZE_TOTAL = 'SERVERLESS_DATA_SIZE_TOTAL',
  /** SERVERLESS_NETWORK_BYTES_IN */
  SERVERLESS_NETWORK_BYTES_IN = 'SERVERLESS_NETWORK_BYTES_IN',
  /** SERVERLESS_NETWORK_BYTES_OUT */
  SERVERLESS_NETWORK_BYTES_OUT = 'SERVERLESS_NETWORK_BYTES_OUT',
  /** SERVERLESS_NETWORK_NUM_REQUESTS */
  SERVERLESS_NETWORK_NUM_REQUESTS = 'SERVERLESS_NETWORK_NUM_REQUESTS',
  /** SERVERLESS_OPCOUNTER_CMD */
  SERVERLESS_OPCOUNTER_CMD = 'SERVERLESS_OPCOUNTER_CMD',
  /** SERVERLESS_OPCOUNTER_DELETE */
  SERVERLESS_OPCOUNTER_DELETE = 'SERVERLESS_OPCOUNTER_DELETE',
  /** SERVERLESS_OPCOUNTER_GETMORE */
  SERVERLESS_OPCOUNTER_GETMORE = 'SERVERLESS_OPCOUNTER_GETMORE',
  /** SERVERLESS_OPCOUNTER_INSERT */
  SERVERLESS_OPCOUNTER_INSERT = 'SERVERLESS_OPCOUNTER_INSERT',
  /** SERVERLESS_OPCOUNTER_QUERY */
  SERVERLESS_OPCOUNTER_QUERY = 'SERVERLESS_OPCOUNTER_QUERY',
  /** SERVERLESS_OPCOUNTER_UPDATE */
  SERVERLESS_OPCOUNTER_UPDATE = 'SERVERLESS_OPCOUNTER_UPDATE',
  /** SERVERLESS_TOTAL_READ_UNITS */
  SERVERLESS_TOTAL_READ_UNITS = 'SERVERLESS_TOTAL_READ_UNITS',
  /** SERVERLESS_TOTAL_WRITE_UNITS */
  SERVERLESS_TOTAL_WRITE_UNITS = 'SERVERLESS_TOTAL_WRITE_UNITS',
  /** SWAP_USAGE_FREE */
  SWAP_USAGE_FREE = 'SWAP_USAGE_FREE',
  /** SWAP_USAGE_USED */
  SWAP_USAGE_USED = 'SWAP_USAGE_USED',
  /** SYSTEM_MEMORY_AVAILABLE */
  SYSTEM_MEMORY_AVAILABLE = 'SYSTEM_MEMORY_AVAILABLE',
  /** SYSTEM_MEMORY_FREE */
  SYSTEM_MEMORY_FREE = 'SYSTEM_MEMORY_FREE',
  /** SYSTEM_MEMORY_USED */
  SYSTEM_MEMORY_USED = 'SYSTEM_MEMORY_USED',
  /** SYSTEM_NETWORK_IN */
  SYSTEM_NETWORK_IN = 'SYSTEM_NETWORK_IN',
  /** SYSTEM_NETWORK_OUT */
  SYSTEM_NETWORK_OUT = 'SYSTEM_NETWORK_OUT',
  /** TICKETS_AVAILABLE_READS */
  TICKETS_AVAILABLE_READS = 'TICKETS_AVAILABLE_READS',
  /** TICKETS_AVAILABLE_WRITES */
  TICKETS_AVAILABLE_WRITES = 'TICKETS_AVAILABLE_WRITES',
}

/**
 * MongoDB Cloud computes the current metric value as an average.
 *
 * @schema MetricThresholdViewMode
 */
export enum MetricThresholdViewMode {
  /** AVERAGE */
  AVERAGE = 'AVERAGE',
}

/**
 * Comparison operator to apply when checking the current metric value.
 *
 * @schema MetricThresholdViewOperator
 */
export enum MetricThresholdViewOperator {
  /** GREATER_THAN */
  GREATER_THAN = 'GREATER_THAN',
  /** LESS_THAN */
  LESS_THAN = 'LESS_THAN',
}

/**
 * Element used to express the quantity. This can be an element of time, storage capacity, and the like.
 *
 * @schema MetricThresholdViewUnits
 */
export enum MetricThresholdViewUnits {
  /** BITS */
  BITS = 'BITS',
  /** BYTES */
  BYTES = 'BYTES',
  /** DAYS */
  DAYS = 'DAYS',
  /** GIGABITS */
  GIGABITS = 'GIGABITS',
  /** GIGABYTES */
  GIGABYTES = 'GIGABYTES',
  /** HOURS */
  HOURS = 'HOURS',
  /** KILOBITS */
  KILOBITS = 'KILOBITS',
  /** KILOBYTES */
  KILOBYTES = 'KILOBYTES',
  /** MEGABITS */
  MEGABITS = 'MEGABITS',
  /** MEGABYTES */
  MEGABYTES = 'MEGABYTES',
  /** MILLISECONDS */
  MILLISECONDS = 'MILLISECONDS',
  /** MINUTES */
  MINUTES = 'MINUTES',
  /** PETABYTES */
  PETABYTES = 'PETABYTES',
  /** RAW */
  RAW = 'RAW',
  /** SECONDS */
  SECONDS = 'SECONDS',
  /** TERABYTES */
  TERABYTES = 'TERABYTES',
}

/**
 * Datadog region that indicates which API Uniform Resource Locator (URL) to use. The resource requires this parameter when '"notifications.typeName" : "DATADOG"'.
 *
 * @schema NotificationViewDatadogRegion
 */
export enum NotificationViewDatadogRegion {
  /** EU */
  EU = 'EU',
  /** US */
  US = 'US',
}

/**
 * Opsgenie region that indicates which API Uniform Resource Locator (URL) to use.
 *
 * @schema NotificationViewOpsGenieRegion
 */
export enum NotificationViewOpsGenieRegion {
  /** EU */
  EU = 'EU',
  /** US */
  US = 'US',
}

/**
 * @schema NotificationViewRoles
 */
export enum NotificationViewRoles {
  /** GROUP_CLUSTER_MANAGER */
  GROUP_CLUSTER_MANAGER = 'GROUP_CLUSTER_MANAGER',
  /** GROUP_DATA_ACCESS_ADMIN */
  GROUP_DATA_ACCESS_ADMIN = 'GROUP_DATA_ACCESS_ADMIN',
  /** GROUP_DATA_ACCESS_READ_ONLY */
  GROUP_DATA_ACCESS_READ_ONLY = 'GROUP_DATA_ACCESS_READ_ONLY',
  /** GROUP_DATA_ACCESS_READ_WRITE */
  GROUP_DATA_ACCESS_READ_WRITE = 'GROUP_DATA_ACCESS_READ_WRITE',
  /** GROUP_OWNER */
  GROUP_OWNER = 'GROUP_OWNER',
  /** GROUP_READ_WRITE */
  GROUP_READ_WRITE = 'GROUP_READ_WRITE',
  /** ORG_OWNER */
  ORG_OWNER = 'ORG_OWNER',
  /** ORG_MEMBER */
  ORG_MEMBER = 'ORG_MEMBER',
  /** ORG_GROUP_CREATOR */
  ORG_GROUP_CREATOR = 'ORG_GROUP_CREATOR',
  /** ORG_BILLING_ADMIN */
  ORG_BILLING_ADMIN = 'ORG_BILLING_ADMIN',
  /** ORG_READ_ONLY */
  ORG_READ_ONLY = 'ORG_READ_ONLY',
}

/**
 * Degree of seriousness given to this notification.
 *
 * @schema NotificationViewSeverity
 */
export enum NotificationViewSeverity {
  /** CRITICAL */
  CRITICAL = 'CRITICAL',
  /** ERROR */
  ERROR = 'ERROR',
  /** WARNING */
  WARNING = 'WARNING',
}

/**
 * Human-readable label that displays the alert notification type.
 *
 * @schema NotificationViewTypeName
 */
export enum NotificationViewTypeName {
  /** DATADOG */
  DATADOG = 'DATADOG',
  /** EMAIL */
  EMAIL = 'EMAIL',
  /** FLOWDOCK */
  FLOWDOCK = 'FLOWDOCK',
  /** GROUP */
  GROUP = 'GROUP',
  /** MICROSOFT_TEAMS */
  MICROSOFT_TEAMS = 'MICROSOFT_TEAMS',
  /** OPS_GENIE */
  OPS_GENIE = 'OPS_GENIE',
  /** ORG */
  ORG = 'ORG',
  /** PAGER_DUTY */
  PAGER_DUTY = 'PAGER_DUTY',
  /** PROMETHEUS */
  PROMETHEUS = 'PROMETHEUS',
  /** SLACK */
  SLACK = 'SLACK',
  /** SMS */
  SMS = 'SMS',
  /** TEAM */
  TEAM = 'TEAM',
  /** USER */
  USER = 'USER',
  /** VICTOR_OPS */
  VICTOR_OPS = 'VICTOR_OPS',
  /** WEBHOOK */
  WEBHOOK = 'WEBHOOK',
}

/**
 * Comparison operator to apply when checking the current metric value.
 *
 * @schema IntegerThresholdViewOperator
 */
export enum IntegerThresholdViewOperator {
  /** GREATER_THAN */
  GREATER_THAN = 'GREATER_THAN',
  /** LESS_THAN */
  LESS_THAN = 'LESS_THAN',
}

/**
 * Element used to express the quantity. This can be an element of time, storage capacity, and the like.
 *
 * @schema IntegerThresholdViewUnits
 */
export enum IntegerThresholdViewUnits {
  /** BITS */
  BITS = 'BITS',
  /** BYTES */
  BYTES = 'BYTES',
  /** DAYS */
  DAYS = 'DAYS',
  /** GIGABITS */
  GIGABITS = 'GIGABITS',
  /** GIGABYTES */
  GIGABYTES = 'GIGABYTES',
  /** HOURS */
  HOURS = 'HOURS',
  /** KILOBITS */
  KILOBITS = 'KILOBITS',
  /** KILOBYTES */
  KILOBYTES = 'KILOBYTES',
  /** MEGABITS */
  MEGABITS = 'MEGABITS',
  /** MEGABYTES */
  MEGABYTES = 'MEGABYTES',
  /** MILLISECONDS */
  MILLISECONDS = 'MILLISECONDS',
  /** MINUTES */
  MINUTES = 'MINUTES',
  /** PETABYTES */
  PETABYTES = 'PETABYTES',
  /** RAW */
  RAW = 'RAW',
  /** SECONDS */
  SECONDS = 'SECONDS',
  /** TERABYTES */
  TERABYTES = 'TERABYTES',
}


/**
 * A CloudFormation `MongoDB::Atlas::AlertConfiguration`
 *
 * @cloudformationResource MongoDB::Atlas::AlertConfiguration
 * @stability external
 */
export class CfnAlertConfiguration extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = 'MongoDB::Atlas::AlertConfiguration';

  /**
   * Resource props.
   */
  public readonly props: CfnAlertConfigurationProps;

  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.Id`
   */
  public readonly attrId: string;
  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.GroupId`
   */
  public readonly attrGroupId: string;
  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.Links`
   */
  public readonly attrLinks: any[];
  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.TypeName`
   */
  public readonly attrTypeName: string;
  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.Created`
   */
  public readonly attrCreated: string;
  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.TotalCount`
   */
  public readonly attrTotalCount: number;
  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.Updated`
   */
  public readonly attrUpdated: string;
  /**
   * Attribute `MongoDB::Atlas::AlertConfiguration.Results`
   */
  public readonly attrResults: any[];

  /**
   * Create a new `MongoDB::Atlas::AlertConfiguration`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: constructs.Construct, id: string, props: CfnAlertConfigurationProps) {
    super(scope, id, { type: CfnAlertConfiguration.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnAlertConfigurationProps(props)! });

    this.props = props;

    this.attrId = cdk.Token.asString(this.getAtt('Id'));
    this.attrGroupId = cdk.Token.asString(this.getAtt('GroupId'));
    this.attrLinks = this.getAtt('Links');
    this.attrTypeName = cdk.Token.asString(this.getAtt('TypeName'));
    this.attrCreated = cdk.Token.asString(this.getAtt('Created'));
    this.attrTotalCount = cdk.Token.asNumber(this.getAtt('TotalCount'));
    this.attrUpdated = cdk.Token.asString(this.getAtt('Updated'));
    this.attrResults = this.getAtt('Results');
  }
}