// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile            *string      `json:",omitempty"`
	Validations        []Validation `json:",omitempty"`
	BindUsername       *string      `json:",omitempty"`
	Status             *string      `json:",omitempty"`
	RequestId          *string      `json:",omitempty"`
	HostName           *string      `json:",omitempty"`
	CaCertificate      *string      `json:",omitempty"`
	AuthzQueryTemplate *string      `json:",omitempty"`
	BindPassword       *string      `json:",omitempty"`
	GroupId            *string      `json:",omitempty"`
	Port               *int         `json:",omitempty"`
}

// Validation is autogenerated from the json schema
type Validation struct {
	Status         *string `json:",omitempty"`
	ValidationType *string `json:",omitempty"`
}
