// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Links                 []Link                           `json:",omitempty"`
	BindUsername          *string                          `json:",omitempty"`
	Status                *string                          `json:",omitempty"`
	Hostname              *string                          `json:",omitempty"`
	ApiKeys               *ApiKeyDefinition                `json:",omitempty"`
	AuthenticationEnabled *bool                            `json:",omitempty"`
	AuthorizationEnabled  *bool                            `json:",omitempty"`
	CaCertificate         *string                          `json:",omitempty"`
	AuthzQueryTemplate    *string                          `json:",omitempty"`
	BindPassword          *string                          `json:",omitempty"`
	CustomerX509          *ApiAtlasCustomerX509View        `json:",omitempty"`
	GroupId               *string                          `json:",omitempty"`
	Port                  *int                             `json:",omitempty"`
	UserToDNMapping       []ApiAtlasNDSUserToDNMappingView `json:",omitempty"`
}

// Link is autogenerated from the json schema
type Link struct {
	Href *string `json:",omitempty"`
	Rel  *string `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}

// ApiAtlasCustomerX509View is autogenerated from the json schema
type ApiAtlasCustomerX509View struct {
	Cas   *string `json:",omitempty"`
	Links []Link  `json:",omitempty"`
}

// ApiAtlasNDSUserToDNMappingView is autogenerated from the json schema
type ApiAtlasNDSUserToDNMappingView struct {
	LdapQuery    *string `json:",omitempty"`
	Match        *string `json:",omitempty"`
	Substitution *string `json:",omitempty"`
}
