package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	ProjectId  *encoding.String      `json:"ProjectId,omitempty"`
	Id         *encoding.String      `json:"Id,omitempty"`
	Whitelist  []WhitelistDefinition `json:"Whitelist,omitempty"`
	ApiKeys    ApiKeyDefinition      `json:"ApiKeys,omitempty"`
	TotalCount *encoding.Int         `json:"TotalCount,omitempty"`
}

// WhitelistDefinition is autogenerated from the json schema
type WhitelistDefinition struct {
	Comment   *encoding.String
	IpAddress *encoding.String
	CidrBlock *encoding.String
	ProjectId *encoding.String
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *encoding.String
	PrivateKey *encoding.String
}
