// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId             *string           `json:",omitempty"`
	ClusterName           *string           `json:",omitempty"`
	Id                    *string           `json:",omitempty"`
	DeliveryType          *string           `json:",omitempty"`
	DeliveryUrl           []string          `json:",omitempty"`
	Cancelled             *bool             `json:",omitempty"`
	CreatedAt             *string           `json:",omitempty"`
	Expired               *bool             `json:",omitempty"`
	ExpiresAt             *string           `json:",omitempty"`
	FinishedAt            *string           `json:",omitempty"`
	Timestamp             *string           `json:",omitempty"`
	SnapshotId            *string           `json:",omitempty"`
	Links                 []Links           `json:",omitempty"`
	OpLogTs               *string           `json:",omitempty"`
	PointInTimeUtcSeconds *int              `json:",omitempty"`
	TargetProjectId       *string           `json:",omitempty"`
	TargetClusterName     *string           `json:",omitempty"`
	ApiKeys               *ApiKeyDefinition `json:",omitempty"`
}

// Links is autogenerated from the json schema
type Links struct {
	Rel  *string `json:",omitempty"`
	Href *string `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
