package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	ProjectId             *encoding.String   `json:"ProjectId,omitempty"`
	ClusterName           *encoding.String   `json:"ClusterName,omitempty"`
	Id                    *encoding.String   `json:"Id,omitempty"`
	DeliveryType          *encoding.String   `json:"DeliveryType,omitempty"`
	DeliveryUrl           []*encoding.String `json:"DeliveryUrl,omitempty"`
	Cancelled             *encoding.Bool     `json:"Cancelled,omitempty"`
	CreatedAt             *encoding.String   `json:"CreatedAt,omitempty"`
	Expired               *encoding.Bool     `json:"Expired,omitempty"`
	ExpiresAt             *encoding.String   `json:"ExpiresAt,omitempty"`
	FinishedAt            *encoding.String   `json:"FinishedAt,omitempty"`
	Timestamp             *encoding.String   `json:"Timestamp,omitempty"`
	SnapshotId            *encoding.String   `json:"SnapshotId,omitempty"`
	Links                 []Links            `json:"Links,omitempty"`
	OpLogTs               *encoding.String   `json:"OpLogTs,omitempty"`
	PointInTimeUtcSeconds *encoding.Int      `json:"PointInTimeUtcSeconds,omitempty"`
	TargetProjectId       *encoding.String   `json:"TargetProjectId,omitempty"`
	TargetClusterName     *encoding.String   `json:"TargetClusterName,omitempty"`
	ApiKeys               ApiKeyDefinition   `json:"ApiKeys,omitempty"`
}

// Links is autogenerated from the json schema
type Links struct {
	Rel  *encoding.String
	Href *encoding.String
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *encoding.String
	PrivateKey *encoding.String
}
