// Copyright 2023 MongoDB Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	GroupId        *string         `json:",omitempty"`
	Actions        []Action        `json:",omitempty"`
	InheritedRoles []InheritedRole `json:",omitempty"`
	RoleName       *string         `json:",omitempty"`
	ApiKeys        *ApiKey         `json:",omitempty"`
}

// Action is autogenerated from the json schema
type Action struct {
	Action    *string    `json:",omitempty"`
	Resources []Resource `json:",omitempty"`
}

// Resource is autogenerated from the json schema
type Resource struct {
	Collection *string `json:",omitempty"`
	DB         *string `json:",omitempty"`
	Cluster    *bool   `json:",omitempty"`
}

// InheritedRole is autogenerated from the json schema
type InheritedRole struct {
	Db   *string `json:",omitempty"`
	Role *string `json:",omitempty"`
}

// ApiKey is autogenerated from the json schema
type ApiKey struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
