// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId      *string         `json:",omitempty"`
	Actions        []Action        `json:",omitempty"`
	InheritedRoles []InheritedRole `json:",omitempty"`
	RoleName       *string         `json:",omitempty"`
	Profile        *string         `json:",omitempty"`
}

// Action is autogenerated from the json schema
type Action struct {
	Action    *string    `json:",omitempty"`
	Resources []Resource `json:",omitempty"`
}

// Resource is autogenerated from the json schema
type Resource struct {
	Collection *string `json:",omitempty"`
	DB         *string `json:",omitempty"`
	Cluster    *bool   `json:",omitempty"`
}

// InheritedRole is autogenerated from the json schema
type InheritedRole struct {
	Db   *string `json:",omitempty"`
	Role *string `json:",omitempty"`
}
