package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	ProjectId  *string               `json:",omitempty"`
	Id         *string               `json:",omitempty"`
	Whitelist  []WhitelistDefinition `json:",omitempty"`
	ApiKeys    *ApiKeyDefinition     `json:",omitempty"`
	TotalCount *int                  `json:",omitempty"`
}

// WhitelistDefinition is autogenerated from the json schema
type WhitelistDefinition struct {
	Comment          *string `json:",omitempty"`
	IpAddress        *string `json:",omitempty"`
	CidrBlock        *string `json:",omitempty"`
	AwsSecurityGroup *string `json:",omitempty"`
	ProjectId        *string `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
