// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId                         *string              `json:",omitempty"`
	ClusterName                       *string              `json:",omitempty"`
	Id                                *string              `json:",omitempty"`
	IdPolicy                          *string              `json:",omitempty"`
	AutoExportEnabled                 *bool                `json:",omitempty"`
	UseOrgAndGroupNamesInExportPrefix *bool                `json:",omitempty"`
	Export                            *Export              `json:",omitempty"`
	CopySettings                      []CopySettings       `json:",omitempty"`
	DeleteCopiedBackup                []DeleteCopiedBackup `json:",omitempty"`
	Policies                          []Policies           `json:",omitempty"`
	ReferenceHourOfDay                *int                 `json:",omitempty"`
	ReferenceMinuteOfHour             *int                 `json:",omitempty"`
	RestoreWindowDays                 *int                 `json:",omitempty"`
	UpdateSnapshots                   *bool                `json:",omitempty"`
	ClusterId                         *string              `json:",omitempty"`
	NextSnapshot                      *string              `json:",omitempty"`
	Links                             []Links              `json:",omitempty"`
	ApiKeys                           *ApiKeyDefinition    `json:",omitempty"`
}

// Export is autogenerated from the json schema
type Export struct {
	ExportBucketId *string `json:",omitempty"`
	FrequencyType  *string `json:",omitempty"`
}

// CopySettings is autogenerated from the json schema
type CopySettings struct {
	CloudProvider     *string  `json:",omitempty"`
	RegionName        *string  `json:",omitempty"`
	ReplicationSpecId *string  `json:",omitempty"`
	ShouldCopyOplogs  *bool    `json:",omitempty"`
	Frequencies       []string `json:",omitempty"`
}

// DeleteCopiedBackup is autogenerated from the json schema
type DeleteCopiedBackup struct {
	CloudProvider     *string `json:",omitempty"`
	RegionName        *string `json:",omitempty"`
	ReplicationSpecId *string `json:",omitempty"`
}

// Policies is autogenerated from the json schema
type Policies struct {
	ID          *string       `json:",omitempty"`
	PolicyItems []PolicyItems `json:",omitempty"`
}

// PolicyItems is autogenerated from the json schema
type PolicyItems struct {
	Id                *string `json:",omitempty"`
	FrequencyType     *string `json:",omitempty"`
	FrequencyInterval *int    `json:",omitempty"`
	RetentionValue    *int    `json:",omitempty"`
	RetentionUnit     *string `json:",omitempty"`
}

// Links is autogenerated from the json schema
type Links struct {
	Rel  *string `json:",omitempty"`
	Href *string `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
