// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile                  *string `json:",omitempty"`
	BucketName               *string `json:",omitempty"`
	ProjectId                *string `json:",omitempty"`
	IamRoleID                *string `json:",omitempty"`
	RequirePrivateNetworking *bool   `json:",omitempty"`
	Id                       *string `json:",omitempty"`
}
