// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId      *string           `json:",omitempty"`
	RegionName     *string           `json:",omitempty"`
	Provisioned    *bool             `json:",omitempty"`
	ProviderName   *string           `json:",omitempty"`
	VpcId          *string           `json:",omitempty"`
	AtlasCIDRBlock *string           `json:",omitempty"`
	Id             *string           `json:",omitempty"`
	ApiKeys        *ApiKeyDefinition `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
