name: Bug report [Recommended Template]
description: Something unexpected happen? Report an error, crash, or an incorrect behavior here.
title: "[Bug]: <your-title>"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue. **These GitHub issues** are only for community reporting and assistance; as such, we don't have a guaranteed SLA.
        

        **If you have an active MongoDB Atlas Support contract**, the best way for us to assist you with the AWS CFN MongoDB Atlas is through a support ticket.

        **Please note:** In order for us to provide the best experience in supporting our customers, we kindly ask to make sure that all the following sections are correctly filled with all the required information. 
        Our support will prioritise issues that contain all the required information that follows the [one-click reproducible issues principle](../../README.md#one-click-reproducible-issues-principle).
  
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered. If the issue has been reported add a reaction, i.e. +1, to the issue.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: cfn_resource_version
    attributes:
      label: CFN Resource version
      description: What CFN resource version are you using in your AWS account?
      placeholder: "Example: v1.6.6"
    validations:
      required: true

  - type: input
    id: cfn_resource_region
    attributes:
      label: CFN Resource Region
      description: In which AWS Region are you running your CFN stack?
      placeholder: "us-east-1"
    validations:
      required: true

  - type: textarea
    id: current_behaviour
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
 
  - type: textarea
    id: tf_config
    attributes:
      label: CFN template to reproduce the issue
      description: Please copy and paste your CFN template. This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false


  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

