// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name              *string                   `json:",omitempty"`
	DataProcessRegion *StreamsDataProcessRegion `json:",omitempty"`
	StreamConfig      *StreamConfig             `json:",omitempty"`
	Id                *string                   `json:",omitempty"`
	Connections       *StreamsConnection        `json:",omitempty"`
	GroupId           *string                   `json:",omitempty"`
	Hostnames         []string                  `json:",omitempty"`
	Links             []Link                    `json:",omitempty"`
}

// StreamsDataProcessRegion is autogenerated from the json schema
type StreamsDataProcessRegion struct {
	CloudProvider *string `json:",omitempty"`
	Links         []Link  `json:",omitempty"`
	Region        *string `json:",omitempty"`
}

// Link is autogenerated from the json schema
type Link struct {
	Href *string `json:",omitempty"`
	Rel  *string `json:",omitempty"`
}

// StreamConfig is autogenerated from the json schema
type StreamConfig struct {
	Links []Link  `json:",omitempty"`
	Tier  *string `json:",omitempty"`
}

// StreamsConnection is autogenerated from the json schema
type StreamsConnection struct {
	Links            []Link                      `json:",omitempty"`
	Name             *string                     `json:",omitempty"`
	Type             *string                     `json:",omitempty"`
	Authentication   *StreamsKafkaAuthentication `json:",omitempty"`
	BootstrapServers *string                     `json:",omitempty"`
	Security         *StreamsKafkaSecurity       `json:",omitempty"`
	ClusterName      *string                     `json:",omitempty"`
	DbRoleToExecute  *DBRoleToExecute            `json:",omitempty"`
}

// StreamsKafkaAuthentication is autogenerated from the json schema
type StreamsKafkaAuthentication struct {
	Links     []Link  `json:",omitempty"`
	Mechanism *string `json:",omitempty"`
	Password  *string `json:",omitempty"`
	Username  *string `json:",omitempty"`
}

// StreamsKafkaSecurity is autogenerated from the json schema
type StreamsKafkaSecurity struct {
	BrokerPublicCertificate *string `json:",omitempty"`
	Links                   []Link  `json:",omitempty"`
	Protocol                *string `json:",omitempty"`
}

// DBRoleToExecute is autogenerated from the json schema
type DBRoleToExecute struct {
	Links []Link  `json:",omitempty"`
	Role  *string `json:",omitempty"`
	Type  *string `json:",omitempty"`
}
