// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name              *string                   `json:",omitempty"`
	DataProcessRegion *StreamsDataProcessRegion `json:",omitempty"`
	StreamConfig      *StreamConfig             `json:",omitempty"`
	Id                *string                   `json:",omitempty"`
	GroupId           *string                   `json:",omitempty"`
	Hostnames         []string                  `json:",omitempty"`
	Links             []Link                    `json:",omitempty"`
}

// StreamsDataProcessRegion is autogenerated from the json schema
type StreamsDataProcessRegion struct {
	CloudProvider *string `json:",omitempty"`
	Links         []Link  `json:",omitempty"`
}

// Link is autogenerated from the json schema
type Link struct {
	Href *string `json:",omitempty"`
	Rel  *string `json:",omitempty"`
}

// StreamConfig is autogenerated from the json schema
type StreamConfig struct {
	Links []Link  `json:",omitempty"`
	Tier  *string `json:",omitempty"`
}
