// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId        *string `json:",omitempty"`
	TenantName       *string `json:",omitempty"`
	LimitName        *string `json:",omitempty"`
	CurrentUsage     *string `json:",omitempty"`
	DefaultLimit     *string `json:",omitempty"`
	LastModifiedDate *string `json:",omitempty"`
	MaximumLimit     *string `json:",omitempty"`
	OverrunPolicy    *string `json:",omitempty"`
	Value            *string `json:",omitempty"`
	Profile          *string `json:",omitempty"`
}
