// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys                  *ApiKeyDefinition `json:",omitempty"`
	ProjectId                *string           `json:",omitempty"`
	Type                     *string           `json:",omitempty"`
	LicenseKey               *string           `json:",omitempty"`
	AccountId                *string           `json:",omitempty"`
	WriteToken               *string           `json:",omitempty"`
	ReadToken                *string           `json:",omitempty"`
	ApiKey                   *string           `json:",omitempty"`
	Region                   *string           `json:",omitempty"`
	ServiceKey               *string           `json:",omitempty"`
	ApiToken                 *string           `json:",omitempty"`
	TeamName                 *string           `json:",omitempty"`
	ChannelName              *string           `json:",omitempty"`
	RoutingKey               *string           `json:",omitempty"`
	FlowName                 *string           `json:",omitempty"`
	OrgName                  *string           `json:",omitempty"`
	Url                      *string           `json:",omitempty"`
	Secret                   *string           `json:",omitempty"`
	MicrosoftTeamsWebhookUrl *string           `json:",omitempty"`
	UserName                 *string           `json:",omitempty"`
	Password                 *string           `json:",omitempty"`
	ServiceDiscovery         *string           `json:",omitempty"`
	Scheme                   *string           `json:",omitempty"`
	Enabled                  *bool             `json:",omitempty"`
	ListenAddress            *string           `json:",omitempty"`
	TlsPemPath               *string           `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}
