package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys                  ApiKeyDefinition  `json:"ApiKeys,omitempty"`
	AutoScaling              AutoScaling       `json:"AutoScaling,omitempty"`
	BackupEnabled            *encoding.Bool    `json:"BackupEnabled,omitempty"`
	BiConenctor              BiConenctor       `json:"BiConenctor,omitempty"`
	ClusterType              *encoding.String  `json:"ClusterType,omitempty"`
	DiskSizeGB               *encoding.Float   `json:"DiskSizeGB,omitempty"`
	EncryptionAtRestProvider *encoding.String  `json:"EncryptionAtRestProvider,omitempty"`
	ProjectID                *encoding.String  `json:"ProjectID,omitempty"`
	ID                       *encoding.String  `json:"ID,omitempty"`
	Labels                   []Labels          `json:"Labels,omitempty"`
	MongoDBVersion           *encoding.String  `json:"MongoDBVersion,omitempty"`
	MongoDBMajorVersion      *encoding.String  `json:"MongoDBMajorVersion,omitempty"`
	MongoURI                 *encoding.String  `json:"MongoURI,omitempty"`
	MongoURIUpdated          *encoding.String  `json:"MongoURIUpdated,omitempty"`
	MongoURIWithOptions      *encoding.String  `json:"MongoURIWithOptions,omitempty"`
	Name                     *encoding.String  `json:"Name,omitempty"`
	NumShards                *encoding.Int     `json:"NumShards,omitempty"`
	Paused                   *encoding.Bool    `json:"Paused,omitempty"`
	PitEnabled               *encoding.Bool    `json:"PitEnabled,omitempty"`
	ProviderBackupEnabled    *encoding.Bool    `json:"ProviderBackupEnabled,omitempty"`
	ProviderSettings         ProviderSettings  `json:"ProviderSettings,omitempty"`
	ReplicationFactor        *encoding.Int     `json:"ReplicationFactor,omitempty"`
	ReplicationSpecs         []ReplicationSpec `json:"ReplicationSpecs,omitempty"`
	SrvAddress               *encoding.String  `json:"SrvAddress,omitempty"`
	StateName                *encoding.String  `json:"StateName,omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *encoding.String
	PrivateKey *encoding.String
}

// AutoScaling is autogenerated from the json schema
type AutoScaling struct {
	Compute       Compute
	DiskGBEnabled *encoding.Bool
}

// Compute is autogenerated from the json schema
type Compute struct {
	Enabled          *encoding.Bool
	ScaleDownEnabled *encoding.Bool
}

// BiConenctor is autogenerated from the json schema
type BiConenctor struct {
	ReadPreference *encoding.String
	Enabled        *encoding.Bool
}

// Labels is autogenerated from the json schema
type Labels struct {
	Key   *encoding.String
	Value *encoding.String
}

// ProviderSettings is autogenerated from the json schema
type ProviderSettings struct {
	AutoScaling         AutoScalingProvider
	BackingProviderName *encoding.String
	DiskIOPS            *encoding.Int
	EncryptEBSVolume    *encoding.Bool
	InstanceSizeName    *encoding.String
	RegionName          *encoding.String
	VolumeType          *encoding.String
}

// AutoScalingProvider is autogenerated from the json schema
type AutoScalingProvider struct {
	Compute AutoScalingProviderCompute
}

// AutoScalingProviderCompute is autogenerated from the json schema
type AutoScalingProviderCompute struct {
	MinInstanceSize *encoding.String
	MaxInstanceSize *encoding.String
}

// ReplicationSpec is autogenerated from the json schema
type ReplicationSpec struct {
	ID            *encoding.String
	NumShards     *encoding.Int
	RegionsConfig []RegionsConfig
	ZoneName      *encoding.String
}

// RegionsConfig is autogenerated from the json schema
type RegionsConfig struct {
	RegionName     *encoding.String
	AnalyticsNodes *encoding.Int
	ElectableNodes *encoding.Int
	Priority       *encoding.Int
	ReadOnlyNodes  *encoding.Int
}
