// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile                    *string         `json:",omitempty"`
	FeatureUsages              []FeatureUsages `json:",omitempty"`
	ProjectId                  *string         `json:",omitempty"`
	RoleId                     *string         `json:",omitempty"`
	IamAssumedRoleArn          *string         `json:",omitempty"`
	IamAwsRegion               *string         `json:",omitempty"`
	AuthorizedDate             *string         `json:",omitempty"`
	CreatedDate                *string         `json:",omitempty"`
	AtlasAWSAccountArn         *string         `json:",omitempty"`
	AtlasAssumedRoleExternalId *string         `json:",omitempty"`
}

// FeatureUsages is autogenerated from the json schema
type FeatureUsages struct {
	FeatureType *string `json:",omitempty"`
	FeatureId   *string `json:",omitempty"`
}
