// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Id                    *string  `json:",omitempty"`
	ProjectId             *string  `json:",omitempty"`
	ProviderName          *string  `json:",omitempty"`
	Vendor                *string  `json:",omitempty"`
	Region                *string  `json:",omitempty"`
	ServiceEndpointId     *string  `json:",omitempty"`
	Arn                   *string  `json:",omitempty"`
	DnsDomain             *string  `json:",omitempty"`
	DnsSubDomain          []string `json:",omitempty"`
	InterfaceEndpointId   *string  `json:",omitempty"`
	InterfaceEndpointName *string  `json:",omitempty"`
	ProviderAccountId     *string  `json:",omitempty"`
	State                 *string  `json:",omitempty"`
	ErrorMessage          *string  `json:",omitempty"`
	Tags                  []Tag    `json:",omitempty"`
	Profile               *string  `json:",omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
