// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile                  *string `json:",omitempty"`
	ProjectId                *string `json:",omitempty"`
	EndpointServiceId        *string `json:",omitempty"`
	Id                       *string `json:",omitempty"`
	EnforceConnectionSuccess *bool   `json:",omitempty"`
	InterfaceEndpointId      *string `json:",omitempty"`
	DeleteRequested          *bool   `json:",omitempty"`
	ConnectionStatus         *string `json:",omitempty"`
	ErrorMessage             *string `json:",omitempty"`
}
