AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the MongoDB::Atlas::SearchDeployment resource type

Globals:
  Function:
    Timeout: 900  # Search deployment operations can take 15+ minutes (UPDATING state transitions are long-running)
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: bin/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: bin/
      Environment: 
        Variables: 
          MODE: Test
          LOG_LEVEL: debug
