// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile                  *string                   `json:",omitempty"`
	ClusterName              *string                   `json:",omitempty"`
	ProjectId                *string                   `json:",omitempty"`
	Id                       *string                   `json:",omitempty"`
	Specs                    []ApiSearchDeploymentSpec `json:",omitempty"`
	StateName                *string                   `json:",omitempty"`
	EncryptionAtRestProvider *string                   `json:",omitempty"`
}

// ApiSearchDeploymentSpec is autogenerated from the json schema
type ApiSearchDeploymentSpec struct {
	InstanceSize *string `json:",omitempty"`
	NodeCount    *int    `json:",omitempty"`
}
