package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	ProjectId           *encoding.String `json:"ProjectId,omitempty"`
	ContainerId         *encoding.String `json:"ContainerId,omitempty"`
	AccepterRegionName  *encoding.String `json:"AccepterRegionName,omitempty"`
	AwsAccountId        *encoding.String `json:"AwsAccountId,omitempty"`
	ProviderName        *encoding.String `json:"ProviderName,omitempty"`
	RouteTableCidrBlock *encoding.String `json:"RouteTableCidrBlock,omitempty"`
	VpcId               *encoding.String `json:"VpcId,omitempty"`
	ConnectionId        *encoding.String `json:"ConnectionId,omitempty"`
	ErrorStateName      *encoding.String `json:"ErrorStateName,omitempty"`
	StatusName          *encoding.String `json:"StatusName,omitempty"`
	Id                  *encoding.String `json:"Id,omitempty"`
	ApiKeys             ApiKeyDefinition `json:"ApiKeys,omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *encoding.String
	PrivateKey *encoding.String
}
