// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	OrgId           *string `json:",omitempty"`
	ClientId        *string `json:",omitempty"`
	CIDRBlock       *string `json:",omitempty"`
	IPAddress       *string `json:",omitempty"`
	CreatedAt       *string `json:",omitempty"`
	LastUsedAddress *string `json:",omitempty"`
	LastUsedAt      *string `json:",omitempty"`
	RequestCount    *int    `json:",omitempty"`
	Profile         *string `json:",omitempty"`
}
