== Test the deployment

There are two ways to test your deployment:

. When the deployment completes, locate the new deployment project ID in the stack outputs, which you can use to open the MongoDB Atlas web console at `\http://cloud.mongodb.com/v2/<ProjectId>`.

. Use the `mongo` shell. For more information, see https://docs.mongodb.com/manual/reference/program/mongo/index.html#connect-to-a-mongodb-atlas-cluster-using-aws-iam-credentials[Connect to a MongoDB Atlas Cluster using AWS IAM Credentials^].

== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

There are many considerations for production-grade deployments. While this Quick Start demonstrates some of these, such as database-user security and peering, see https://docs.atlas.mongodb.com/best-practices/[Atlas Production Best Practices^] for the latest information.

Choosing the correct Atlas cluster tier and configuration is an important step in setting up a successful production MongoDB deployment. You can always modify a cluster at a later time, but getting started with the right configuration is possible with a few calculations based on your data set size and network requirements. For more information, see https://docs.atlas.mongodb.com/production-considerations/[MongoDB Atlas Production Considerations^].

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

This Quick Start provisions a cluster with security and TLS enabled by default. Optionally, network peering can be enabled on a new or existing AWS VPC. For more information, see https://docs.atlas.mongodb.com/setup-cluster-security/[MongoDB Security Features and Setup^].

If you plan to use AWS Lambda, ensure that you follow the recommendations from https://docs.atlas.mongodb.com/best-practices-connecting-to-aws-lambda/[Best Practices Connecting from AWS Lambda^].

//== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

=== MongoDB Atlas CloudFormation resource reference

- *MongoDB::Atlas::Project* — A logical grouping of clusters. You can have multiple clusters within a single project and multiple projects within a single organization.

- *MongoDB::Atlas::Cluster* — A set of nodes comprising a MongoDB deployment and database. In Atlas, clusters can be replica sets or sharded deployments.

- *MongoDB::Atlas::DatabaseUser* — Credentials used to authenticate a client to access a MongoDB database deployment. You can assign privileges to a database user to determine a user's access level to a cluster. Database users are different from Atlas users. Database users have access to MongoDB deployments but not the Atlas application.

- *MongoDB::Atlas::ProjectIPAccessList* — Atlas allows only client connections to the cluster from entries in the project's IP access list. Each entry is either a single IP address or CIDR. 

- *MongoDB::Atlas::NetworkPeering* — Process by which two internet networks connect and exchange traffic. You can directly peer your VPC with the Atlas VPC created for your MongoDB clusters. Using network peering, your application servers can connect directly to Atlas while remaining isolated from public networks.

For more information, see https://github.com/aws-quickstart/quickstart-mongodb-atlas-resources/tree/main/cfn-resources/project/docs[MongoDB::Atlas::Project^], https://docs.atlas.mongodb.com/reference/api/projects/[MongoDB Projects^], and https://docs.atlas.mongodb.com/mongodb-reference/[MongoDB Reference^].


