// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	CreatedByUser     *ApiAtlasUserMetadata `json:",omitempty"`
	CreatedDate       *string               `json:",omitempty"`
	Id                *string               `json:",omitempty"`
	LastUpdatedByUser *ApiAtlasUserMetadata `json:",omitempty"`
	LastUpdatedDate   *string               `json:",omitempty"`
	Name              *string               `json:",omitempty"`
	Description       *string               `json:",omitempty"`
	OrgId             *string               `json:",omitempty"`
	Policies          []ApiAtlasPolicy      `json:",omitempty"`
	Version           *string               `json:",omitempty"`
	Profile           *string               `json:",omitempty"`
}

// ApiAtlasUserMetadata is autogenerated from the json schema
type ApiAtlasUserMetadata struct {
	Id   *string `json:",omitempty"`
	Name *string `json:",omitempty"`
}

// ApiAtlasPolicy is autogenerated from the json schema
type ApiAtlasPolicy struct {
	Body *string `json:",omitempty"`
	Id   *string `json:",omitempty"`
}
