// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile         *string  `json:",omitempty"`
	CreatedAt       *string  `json:",omitempty"`
	ExpiresAt       *string  `json:",omitempty"`
	Id              *string  `json:",omitempty"`
	IncludeCount    *bool    `json:",omitempty"`
	InvitationId    *string  `json:",omitempty"`
	InviterUsername *string  `json:",omitempty"`
	ItemsPerPage    *int     `json:",omitempty"`
	OrgId           *string  `json:",omitempty"`
	OrgName         *string  `json:",omitempty"`
	PageNum         *int     `json:",omitempty"`
	Roles           []string `json:",omitempty"`
	TeamIds         []string `json:",omitempty"`
	TotalCount      *float64 `json:",omitempty"`
	Username        *string  `json:",omitempty"`
}
