// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys              *ApiKeyDefinition `json:",omitempty"`
	ExternalGroupName    *string           `json:",omitempty"`
	FederationSettingsId *string           `json:",omitempty"`
	Id                   *string           `json:",omitempty"`
	OrgId                *string           `json:",omitempty"`
	RoleAssignments      []RoleAssignment  `json:",omitempty"`
	ListOptions          *ListOptions      `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}

// RoleAssignment is autogenerated from the json schema
type RoleAssignment struct {
	ApiKeys *ApiKeyDefinition `json:",omitempty"`
	GroupId *string           `json:",omitempty"`
	OrgId   *string           `json:",omitempty"`
	Role    *string           `json:",omitempty"`
}

// ListOptions is autogenerated from the json schema
type ListOptions struct {
	PageNum      *int  `json:",omitempty"`
	IncludeCount *bool `json:",omitempty"`
	ItemsPerPage *int  `json:",omitempty"`
}
