// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId  *string                `json:",omitempty"`
	Id         *string                `json:",omitempty"`
	AccessList []AccessListDefinition `json:",omitempty"`
	ApiKeys    *ApiKeyDefinition      `json:",omitempty"`
	TotalCount *int                   `json:",omitempty"`
}

// AccessListDefinition is autogenerated from the json schema
type AccessListDefinition struct {
	Comment          *string `json:",omitempty"`
	IPAddress        *string `json:",omitempty"`
	CIDRBlock        *string `json:",omitempty"`
	AwsSecurityGroup *string `json:",omitempty"`
	ProjectId        *string `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PublicKey  *string `json:",omitempty"`
	PrivateKey *string `json:",omitempty"`
}
