// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name                      *string `json:",omitempty"`
	APIKey                    *APIKey `json:",omitempty"`
	FederatedSettingsId       *string `json:",omitempty"`
	OrgOwnerId                *string `json:",omitempty"`
	Profile                   *string `json:",omitempty"`
	AwsSecretName             *string `json:",omitempty"`
	SkipDefaultAlertsSettings *bool   `json:",omitempty"`
	GenAIFeaturesEnabled      *bool   `json:",omitempty"`
	OrgId                     *string `json:",omitempty"`
	IsDeleted                 *bool   `json:",omitempty"`
	ApiAccessListRequired     *bool   `json:",omitempty"`
	MultiFactorAuthRequired   *bool   `json:",omitempty"`
	RestrictEmployeeAccess    *bool   `json:",omitempty"`
	SecurityContact           *string `json:",omitempty"`
}

// APIKey is autogenerated from the json schema
type APIKey struct {
	Description *string  `json:",omitempty"`
	Roles       []string `json:",omitempty"`
}
