// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Analyzer       *string                                   `json:",omitempty"`
	Analyzers      []ApiAtlasFTSAnalyzersViewManual          `json:",omitempty"`
	Profile        *string                                   `json:",omitempty"`
	ClusterName    *string                                   `json:",omitempty"`
	CollectionName *string                                   `json:",omitempty"`
	Database       *string                                   `json:",omitempty"`
	ProjectId      *string                                   `json:",omitempty"`
	IndexId        *string                                   `json:",omitempty"`
	Mappings       *ApiAtlasFTSMappingsViewManual            `json:",omitempty"`
	Name           *string                                   `json:",omitempty"`
	Type           *string                                   `json:",omitempty"`
	SearchAnalyzer *string                                   `json:",omitempty"`
	Status         *string                                   `json:",omitempty"`
	Synonyms       []ApiAtlasFTSSynonymMappingDefinitionView `json:",omitempty"`
	Fields         *string                                   `json:",omitempty"`
	StoredSource   *string                                   `json:",omitempty"`
	TypeSets       []TypeSet                                 `json:",omitempty"`
	NumPartitions  *int                                      `json:",omitempty"`
}

// ApiAtlasFTSAnalyzersViewManual is autogenerated from the json schema
type ApiAtlasFTSAnalyzersViewManual struct {
	CharFilters  []string                       `json:",omitempty"`
	Name         *string                        `json:",omitempty"`
	TokenFilters []string                       `json:",omitempty"`
	Tokenizer    *ApiAtlasFTSAnalyzersTokenizer `json:",omitempty"`
}

// ApiAtlasFTSAnalyzersTokenizer is autogenerated from the json schema
type ApiAtlasFTSAnalyzersTokenizer struct {
	MaxGram        *int    `json:",omitempty"`
	MinGram        *int    `json:",omitempty"`
	Type           *string `json:",omitempty"`
	Group          *int    `json:",omitempty"`
	Pattern        *string `json:",omitempty"`
	MaxTokenLength *int    `json:",omitempty"`
}

// ApiAtlasFTSMappingsViewManual is autogenerated from the json schema
type ApiAtlasFTSMappingsViewManual struct {
	Dynamic       *bool   `json:",omitempty"`
	DynamicConfig *string `json:",omitempty"`
	Fields        *string `json:",omitempty"`
}

// ApiAtlasFTSSynonymMappingDefinitionView is autogenerated from the json schema
type ApiAtlasFTSSynonymMappingDefinitionView struct {
	Analyzer *string        `json:",omitempty"`
	Name     *string        `json:",omitempty"`
	Source   *SynonymSource `json:",omitempty"`
}

// SynonymSource is autogenerated from the json schema
type SynonymSource struct {
	Collection *string `json:",omitempty"`
}

// TypeSet is autogenerated from the json schema
type TypeSet struct {
	Name  *string `json:",omitempty"`
	Types *string `json:",omitempty"`
}
