// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	OrgId      *string `json:",omitempty"`
	APIUserId  *string `json:",omitempty"`
	Profile    *string `json:",omitempty"`
	CidrBlock  *string `json:",omitempty"`
	Entry      *string `json:",omitempty"`
	IpAddress  *string `json:",omitempty"`
	TotalCount *int    `json:",omitempty"`
}
