AWSTemplateFormatVersion: '2010-09-09'
Description: > 
 This template creates the IAM role to use to run the quickstart template on a CFN stack.
 It is optional to pass IAM role to CloudFormation while creating a stack. If you don't supply one, the user permissions are assumed. 
 See the IAM permissions section in the General information guide for more information: https://aws-ia.github.io/content/qs_info.html#_technical_requirements
Resources:
 AtlasQuickstartIAMRole:
  Type: 'AWS::IAM::Role'
  Properties:
   AssumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
    - Effect: Allow
      Principal:
       Service:
       - "lambda.amazonaws.com"
       - "resources.cloudformation.amazonaws.com"
       - "cloudformation.amazonaws.com"
      Action: sts:AssumeRole
   Path: /
   Policies:
   - PolicyName: AtlasQuickstartPolicy
     PolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action:
        - iam:PassRole
        - iam:DeleteRolePolicy
        - iam:AttachRolePolicy
        - iam:CreateRole
        - iam:PutRolePolicy
        - iam:DeleteRole
        - iam:GetRole
        - iam:GetRolePolicy
        - iam:DetachRolePolicy
        Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/*"
      - Effect: Allow
        Action: cloudformation:*
        Resource: '*'
      - Effect: Allow
        Action: ec2:*
        Resource: '*'
      - Effect: Allow
        Action: logs:*
        Resource: '*'
      - Effect: Allow
        Action: servicediscovery:*
        Resource: '*'
      - Effect: Allow
        Action: route53:*
        Resource: '*'
      - Effect: Allow
        Action:
        - secretsmanager:CreateSecret
        - secretsmanager:DeleteSecret
        - secretsmanager:DescribeSecret
        - secretsmanager:GetSecretValue
        - secretsmanager:ListSecrets
        - secretsmanager:PutSecretValue
        - secretsmanager:TagResource
        Resource: '*'
