// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId        *string                     `json:",omitempty"`
	Profile          *string                     `json:",omitempty"`
	ConnectionName   *string                     `json:",omitempty"`
	InstanceName     *string                     `json:",omitempty"`
	Type             *string                     `json:",omitempty"`
	ClusterName      *string                     `json:",omitempty"`
	DbRoleToExecute  *DBRoleToExecute            `json:",omitempty"`
	Authentication   *StreamsKafkaAuthentication `json:",omitempty"`
	BootstrapServers *string                     `json:",omitempty"`
	Security         *StreamsKafkaSecurity       `json:",omitempty"`
	Config           map[string]string           `json:",omitempty"`
}

// DBRoleToExecute is autogenerated from the json schema
type DBRoleToExecute struct {
	Role *string `json:",omitempty"`
	Type *string `json:",omitempty"`
}

// StreamsKafkaAuthentication is autogenerated from the json schema
type StreamsKafkaAuthentication struct {
	Mechanism *string `json:",omitempty"`
	Username  *string `json:",omitempty"`
	Password  *string `json:",omitempty"`
}

// StreamsKafkaSecurity is autogenerated from the json schema
type StreamsKafkaSecurity struct {
	BrokerPublicCertificate *string `json:",omitempty"`
	Protocol                *string `json:",omitempty"`
}
