// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectId        *string                     `json:",omitempty"`
	Profile          *string                     `json:",omitempty"`
	ConnectionName   *string                     `json:",omitempty"`
	InstanceName     *string                     `json:",omitempty"`
	WorkspaceName    *string                     `json:",omitempty"`
	Type             *string                     `json:",omitempty"`
	ClusterName      *string                     `json:",omitempty"`
	ClusterProjectId *string                     `json:",omitempty"`
	DbRoleToExecute  *DBRoleToExecute            `json:",omitempty"`
	Authentication   *StreamsKafkaAuthentication `json:",omitempty"`
	BootstrapServers *string                     `json:",omitempty"`
	Security         *StreamsKafkaSecurity       `json:",omitempty"`
	Config           map[string]string           `json:",omitempty"`
	Networking       *Networking                 `json:",omitempty"`
	Aws              *Aws                        `json:",omitempty"`
	Url              *string                     `json:",omitempty"`
	Headers          map[string]string           `json:",omitempty"`
}

// DBRoleToExecute is autogenerated from the json schema
type DBRoleToExecute struct {
	Role *string `json:",omitempty"`
	Type *string `json:",omitempty"`
}

// StreamsKafkaAuthentication is autogenerated from the json schema
type StreamsKafkaAuthentication struct {
	Mechanism                 *string `json:",omitempty"`
	Method                    *string `json:",omitempty"`
	Username                  *string `json:",omitempty"`
	Password                  *string `json:",omitempty"`
	TokenEndpointUrl          *string `json:",omitempty"`
	ClientId                  *string `json:",omitempty"`
	ClientSecret              *string `json:",omitempty"`
	Scope                     *string `json:",omitempty"`
	SaslOauthbearerExtensions *string `json:",omitempty"`
}

// StreamsKafkaSecurity is autogenerated from the json schema
type StreamsKafkaSecurity struct {
	BrokerPublicCertificate *string `json:",omitempty"`
	Protocol                *string `json:",omitempty"`
}

// Networking is autogenerated from the json schema
type Networking struct {
	Access *Access `json:",omitempty"`
}

// Access is autogenerated from the json schema
type Access struct {
	Type         *string `json:",omitempty"`
	ConnectionId *string `json:",omitempty"`
}

// Aws is autogenerated from the json schema
type Aws struct {
	RoleArn *string `json:",omitempty"`
}
