// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	DeleteAfterDate   *string           `json:",omitempty"`
	AWSIAMType        *string           `json:",omitempty"`
	DatabaseName      *string           `json:",omitempty"`
	Description       *string           `json:",omitempty"`
	Labels            []LabelDefinition `json:",omitempty"`
	LdapAuthType      *string           `json:",omitempty"`
	X509Type          *string           `json:",omitempty"`
	OIDCAuthType      *string           `json:",omitempty"`
	Password          *string           `json:",omitempty"`
	ProjectId         *string           `json:",omitempty"`
	Roles             []RoleDefinition  `json:",omitempty"`
	Scopes            []ScopeDefinition `json:",omitempty"`
	UserCFNIdentifier *string           `json:",omitempty"`
	Username          *string           `json:",omitempty"`
	Profile           *string           `json:",omitempty"`
}

// LabelDefinition is autogenerated from the json schema
type LabelDefinition struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}

// RoleDefinition is autogenerated from the json schema
type RoleDefinition struct {
	CollectionName *string `json:",omitempty"`
	DatabaseName   *string `json:",omitempty"`
	RoleName       *string `json:",omitempty"`
}

// ScopeDefinition is autogenerated from the json schema
type ScopeDefinition struct {
	Name *string `json:",omitempty"`
	Type *string `json:",omitempty"`
}
