package resource

import "github.com/aws-cloudformation/aws-cloudformation-rpdk-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	DatabaseName *encoding.String  `json:"DatabaseName,omitempty"`
	Labels       []LabelDefinition `json:"Labels,omitempty"`
	LdapAuthType *encoding.String  `json:"LdapAuthType,omitempty"`
	GroupId      *encoding.String  `json:"GroupId,omitempty"`
	Roles        []RoleDefinition  `json:"Roles,omitempty"`
	Password     *encoding.String  `json:"Password,omitempty"`
	Username     *encoding.String  `json:"Username,omitempty"`
}

// LabelDefinition is autogenerated from the json schema
type LabelDefinition struct {
	Key   *encoding.String
	Value *encoding.String
}

// RoleDefinition is autogenerated from the json schema
type RoleDefinition struct {
	CollectionName *encoding.String
	DatabaseName   *encoding.String
	RoleName       *encoding.String
}
