// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Profile              *string            `json:",omitempty"`
	ProjectId            *string            `json:",omitempty"`
	ClusterName          *string            `json:",omitempty"`
	ManagedNamespaces    []ManagedNamespace `json:",omitempty"`
	RemoveAllZoneMapping *bool              `json:",omitempty"`
	CustomZoneMappings   []ZoneMapping      `json:",omitempty"`
}

// ManagedNamespace is autogenerated from the json schema
type ManagedNamespace struct {
	Collection             *string `json:",omitempty"`
	CustomShardKey         *string `json:",omitempty"`
	Db                     *string `json:",omitempty"`
	IsCustomShardKeyHashed *bool   `json:",omitempty"`
	IsShardKeyUnique       *bool   `json:",omitempty"`
}

// ZoneMapping is autogenerated from the json schema
type ZoneMapping struct {
	Location *string `json:",omitempty"`
	Zone     *string `json:",omitempty"`
}
