// Copyright 2023 MongoDB Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys   *ApiKeyDefinition `json:",omitempty"`
	RoleNames []string          `json:",omitempty"`
	OrgId     *string           `json:",omitempty"`
	GroupId   *string           `json:",omitempty"`
	TeamId    *string           `json:",omitempty"`
	Name      *string           `json:",omitempty"`
	Usernames []string          `json:",omitempty"`
	Users     []AtlasUser       `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}

// AtlasUser is autogenerated from the json schema
type AtlasUser struct {
	Country      *string     `json:",omitempty"`
	EmailAddress *string     `json:",omitempty"`
	FirstName    *string     `json:",omitempty"`
	Id           *string     `json:",omitempty"`
	LastName     *string     `json:",omitempty"`
	Links        []Link      `json:",omitempty"`
	MobileNumber *string     `json:",omitempty"`
	Password     *string     `json:",omitempty"`
	Roles        []AtlasRole `json:",omitempty"`
	TeamIds      []string    `json:",omitempty"`
	Username     *string     `json:",omitempty"`
}

// Link is autogenerated from the json schema
type Link struct {
	Rel  *string `json:",omitempty"`
	Href *string `json:",omitempty"`
}

// AtlasRole is autogenerated from the json schema
type AtlasRole struct {
	GroupId  *string `json:",omitempty"`
	OrgId    *string `json:",omitempty"`
	RoleName *string `json:",omitempty"`
}
