name: 'Contract Testing'
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Up Atlas CLI
      uses: andreaangiolillo/atlas-cli-github-action@main
      with:
       public-key: ${{ secrets.CLOUD_DEV_PUBLIC_KEY }}
       private-key: ${{ secrets.CLOUD_DEV_PRIVATE_KEY }}
       org-id: ${{ vars.CLOUD_DEV_ORG_ID }}

    - name: Set up SAM
      run: |
        curl https://github.com/aws/aws-sam-cli/releases/download/v1.76.0/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli.zip
        unzip aws-sam-cli.zip -d sam-installation
        sudo ./sam-installation/install
#
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
#
    - name: Run the Contract test
      shell: bash
      run: |
       pushd cfn-resources/project
       make create-test-resources
     
  
